package com.gpstore.db;

import jakarta.persistence.EntityManager;
import jakarta.persistence.Query;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.transaction.annotation.Transactional;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * A CONSTRAINT DECLARED INSIDE {@code CREATE TABLE IF NOT EXISTS} DOES NOT
 * EXIST ON A FRESH DATABASE, AND THIS IS THE TEST THAT SAYS SO.
 *
 * <p>THE CLASS OF BUG. This schema is built Hibernate-first - the entity
 * tables come from ddl-auto and the versioned scripts decorate them afterwards
 * (see {@code FlywayAfterSchemaConfig} and {@code db/migration/README.md}).
 * Against a table Hibernate has already created, a migration's
 * {@code CREATE TABLE IF NOT EXISTS} is a no-op, and every CHECK declared
 * inside its body is silently skipped. The shop's own database HAS those
 * constraints, because its tables predate the migrations; a newly provisioned
 * one does not.
 *
 * <p>That is the worst shape a schema difference can take: the environment you
 * would test on is the one WITHOUT the guard. An audit found ten of them -
 * a price that could be zero, a rating outside one to five, a preferred-shop
 * slot that could be 7, an appeal outcome with no appeal - all enforcing in
 * production and all absent anywhere new. V64 adds them back.
 *
 * <p>WHAT THIS TEST DOES. It reads every migration, finds every named
 * constraint declared inside a {@code CREATE TABLE} body, and checks the live
 * database actually has it. Writing another one inside a CREATE TABLE now
 * fails the build with the constraint's own name in the message, rather than
 * being discovered years later by somebody standing up a new environment.
 *
 * <p>THE EXEMPTIONS ARE NAMED, NOT INFERRED. Hibernate emits its own CHECK for
 * every {@code @Enumerated} column, with the same value set under a generated
 * name, so a handful of the declared constraints are genuinely enforced
 * twice-over and re-adding them would be noise. Those are listed below with
 * the name that covers them. Anything not on that list has to really exist.
 */
@SpringBootTest(properties = {
        "outbox.initial-delay-ms=3600000",
        "outbox.drain-interval-ms=3600000",
        "payment.expiry-initial-delay-ms=3600000",
        "payment.expiry-interval-ms=3600000"
})
class ConstraintsDeclaredInsideCreateTableTest {

    private static final Path MIGRATIONS = Path.of("src/main/resources/db/migration");

    /**
     * Declared under one name, enforced under another.
     *
     * <p>Every entry is a value-set check on an {@code @Enumerated} column that
     * Hibernate generates itself. The key is what the migration called it; the
     * value is why its absence is not a gap. A new entry here needs the same
     * kind of justification - "it is also enforced, and here is by what" - not
     * simply "the test was failing".
     */
    private static final Map<String, String> ENFORCED_UNDER_ANOTHER_NAME = new LinkedHashMap<>();

    static {
        ENFORCED_UNDER_ANOTHER_NAME.put("ck_dues_status",
                "customer_cancellation_dues_status_check, generated by Hibernate for the enum");
        ENFORCED_UNDER_ANOTHER_NAME.put("ck_billing_plan_tier",
                "billing_plan_tier_check, generated by Hibernate for the enum");
        ENFORCED_UNDER_ANOTHER_NAME.put("ck_billing_period_status",
                "billing_period_status_check, generated by Hibernate for the enum");
        ENFORCED_UNDER_ANOTHER_NAME.put("ck_ledger_entry_type",
                "merchant_ledger_entry_entry_type_check, generated by Hibernate for the enum");
        ENFORCED_UNDER_ANOTHER_NAME.put("ck_governance_level",
                "merchant_governance_actions_level_check, generated by Hibernate for the enum");
        ENFORCED_UNDER_ANOTHER_NAME.put("ck_governance_appeal_outcome",
                "merchant_governance_actions_appeal_outcome_check, generated by Hibernate for the enum");
        ENFORCED_UNDER_ANOTHER_NAME.put("uq_search_synonym_term",
                "a Hibernate-generated UNIQUE over the same column");
        ENFORCED_UNDER_ANOTHER_NAME.put("uk_shop_product_variant",
                "present under its own name; listed only because it is a UNIQUE rather than a CHECK");
        ENFORCED_UNDER_ANOTHER_NAME.put("uk_shop_staff",
                "present under its own name; listed only because it is a UNIQUE rather than a CHECK");
    }

    @Autowired private EntityManager entityManager;

    /** One named constraint, as a migration declared it. */
    private record Declared(String name, String table, String migration) {}

    @Test
    @DisplayName("every constraint a migration declares inside CREATE TABLE exists in the database")
    @Transactional(readOnly = true)
    void nothingDeclaredInsideACreateTableIsMissing() throws IOException {
        List<Declared> declared = declaredInsideCreateTable();

        assertFalse(declared.isEmpty(),
                "No constraints were parsed out of the migrations at all. The parser has "
                        + "stopped matching and this test is now checking nothing.");

        List<String> missing = new ArrayList<>();
        for (Declared d : declared) {
            if (ENFORCED_UNDER_ANOTHER_NAME.containsKey(d.name())) {
                continue;
            }
            if (!constraintExists(d.name(), d.table())) {
                missing.add(d.name() + " on " + d.table() + " (declared in " + d.migration() + ")");
            }
        }

        assertTrue(missing.isEmpty(),
                "These constraints are declared inside a CREATE TABLE IF NOT EXISTS and do NOT "
                        + "exist in this database:\n  " + String.join("\n  ", missing)
                        + "\n\nAgainst a table Hibernate has already created, that whole statement "
                        + "is a no-op, so the constraint is skipped - present on the shop's "
                        + "database, absent on every new one. Add it with an ALTER TABLE in a new "
                        + "migration, the way V64 does, rather than leaving it inside the "
                        + "CREATE TABLE.");
    }

    /**
     * THE CONTROL. A test that reports "nothing missing" is worthless if its
     * existence check answers yes to everything, so it has to answer no to a
     * constraint that is definitely not there.
     */
    @Test
    @DisplayName("and the existence check can actually say no")
    @Transactional(readOnly = true)
    void theCheckWouldHaveNoticed() {
        assertFalse(constraintExists("ck_this_constraint_was_never_written", "shops"),
                "The existence query reports a constraint that does not exist, so a clean run "
                        + "of the test above means nothing.");
        assertTrue(constraintExists("ck_shop_rating_range", "shop_ratings"),
                "One of the constraints V64 adds is missing, so either V64 did not run or it "
                        + "did not do what it says.");
    }

    private boolean constraintExists(String name, String table) {
        Query query = entityManager.createNativeQuery("""
                SELECT count(*) FROM pg_constraint
                WHERE conname = :name AND conrelid = to_regclass(:tbl)
                """);
        query.setParameter("name", name);
        query.setParameter("tbl", table);
        return ((Number) query.getSingleResult()).intValue() > 0;
    }

    /**
     * Every {@code CONSTRAINT <name> CHECK|UNIQUE} written inside a
     * {@code CREATE TABLE IF NOT EXISTS <table> ( ... )} body.
     *
     * <p>Parentheses are balanced rather than matched with one regex, because a
     * CHECK predicate contains its own brackets and a lazy match would stop at
     * the first of them.
     */
    private static List<Declared> declaredInsideCreateTable() throws IOException {
        Pattern createTable = Pattern.compile(
                "CREATE TABLE IF NOT EXISTS\\s+(\\w+)\\s*\\(", Pattern.CASE_INSENSITIVE);
        Pattern constraint = Pattern.compile(
                "CONSTRAINT\\s+(\\w+)\\s+(CHECK|UNIQUE)", Pattern.CASE_INSENSITIVE);

        List<Declared> found = new ArrayList<>();
        List<Path> files;
        try (Stream<Path> stream = Files.list(MIGRATIONS)) {
            files = stream.filter(p -> p.getFileName().toString().matches("V\\d+__.*\\.sql"))
                    .sorted(Comparator.comparing(p -> p.getFileName().toString()))
                    .toList();
        }

        for (Path file : files) {
            String sql = Files.readString(file);
            Matcher table = createTable.matcher(sql);
            while (table.find()) {
                int open = table.end() - 1;
                int depth = 0;
                int close = -1;
                for (int i = open; i < sql.length(); i++) {
                    char c = sql.charAt(i);
                    if (c == '(') {
                        depth++;
                    } else if (c == ')') {
                        depth--;
                        if (depth == 0) {
                            close = i;
                            break;
                        }
                    }
                }
                if (close < 0) {
                    continue;
                }
                Matcher inside = constraint.matcher(sql.substring(open + 1, close));
                while (inside.find()) {
                    found.add(new Declared(inside.group(1).toLowerCase(),
                            table.group(1).toLowerCase(),
                            file.getFileName().toString()));
                }
            }
        }
        return found;
    }
}
