package com.gpstore.db;

import com.gpstore.config.IdentitySequenceGuard;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import com.gpstore.security.WithStaff;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;

/**
 * The bug: admin "Add Product" answered 409 "That conflicts with something
 * that already exists" for every product, including names that collide with
 * nothing. There is no unique constraint on products.name - the conflict was
 * on products_pkey.
 *
 * Hibernate's @GeneratedValue(IDENTITY) maps to GENERATED BY DEFAULT AS
 * IDENTITY, which lets an INSERT supply its own id without advancing the
 * sequence behind the column. A restored dump, a CSV import or one row typed
 * into a SQL console leaves the sequence behind the table forever, and every
 * insert the application makes from then on asks for an id that is taken.
 *
 * This drives the real thing: a real Postgres, the real POST /api/products
 * endpoint the admin screen calls, and the real payload
 * AdminProductsRepository.createProduct sends. The drift is created the same
 * way a restore creates it - by winding the sequence back below max(id) -
 * rather than by mocking a repository, because a mock cannot reproduce a
 * constraint that only exists in the database.
 */
@SpringBootTest(properties = {
        "outbox.initial-delay-ms=3600000",
        "outbox.drain-interval-ms=3600000",
        "payment.expiry-initial-delay-ms=3600000",
        "idempotency.cleanup-initial-delay-ms=3600000",
        "otp.cleanup-initial-delay-ms=3600000",
        "delivery.late-flag-initial-delay-ms=3600000",
        // The guard is what is under test here - it must not silently repair
        // the drift these tests deliberately create before they observe it.
        "app.identity-sequence-guard.enabled=false"
})
@AutoConfigureMockMvc
class IdentitySequenceDriftTest {

    @Autowired private MockMvc mockMvc;
    @Autowired private JdbcTemplate jdbc;
    @Autowired private IdentitySequenceGuard guard;

    private long categoryId;

    @org.junit.jupiter.api.BeforeEach
    void ownCategory() {
        jdbc.update("INSERT INTO categories (name, active) VALUES ('DriftTest category', true)");
        Long id = jdbc.queryForObject(
                "SELECT max(id) FROM categories WHERE name = 'DriftTest category'", Long.class);
        assertNotNull(id);
        categoryId = id;
    }

    @AfterEach
    void leaveTheSequenceUsable() {
        // Whatever a test did, no other test may inherit a broken sequence.
        guard.resync();
        jdbc.update("DELETE FROM products WHERE name LIKE 'DriftTest %'");
        jdbc.update("DELETE FROM categories WHERE name = 'DriftTest category'");
    }

    private long maxProductId() {
        Long max = jdbc.queryForObject("SELECT COALESCE(max(id), 0) FROM products", Long.class);
        return max == null ? 0 : max;
    }

    private long sequenceValue() {
        Long v = jdbc.queryForObject(
                "SELECT COALESCE(pg_sequence_last_value('products_id_seq'::regclass), 0)", Long.class);
        return v == null ? 0 : v;
    }

    /** Exactly what a dump restore that preserves ids leaves behind. */
    private void windSequenceBackBelowTheTable() {
        Long occupied = jdbc.queryForObject("SELECT COALESCE(max(id), 0) FROM products", Long.class);
        long nextTaken = occupied == null || occupied < 1 ? 1 : occupied;
        jdbc.queryForObject("SELECT setval('products_id_seq', ?, false)", Long.class, nextTaken);
    }

    private long ensureAProductExists() {
        if (maxProductId() == 0) {
            jdbc.update("INSERT INTO products (name, active) VALUES ('DriftTest anchor', true)");
        }
        return maxProductId();
    }

    private MvcResult postProduct(String name) throws Exception {
        // Byte for byte the body AdminProductsRepository.createProduct sends.
        String body = """
                {"name":"%s","brand":"Tata","category":{"id":%d},"active":true}
                """.formatted(name, categoryId);
        return mockMvc.perform(post("/api/products")
                        .contentType("application/json")
                        .content(body))
                .andReturn();
    }

    @Test
    @WithStaff
    @DisplayName("a sequence behind its table makes every Add Product fail - and it is not the admin's fault")
    void driftBreaksProductCreation() throws Exception {
        ensureAProductExists();
        windSequenceBackBelowTheTable();
        assertTrue(sequenceValue() < maxProductId(),
                "precondition: the sequence must be behind the table for this test to mean anything");

        MvcResult result = postProduct("DriftTest Besan");
        String responseBody = result.getResponse().getContentAsString();

        assertNotEquals(200, result.getResponse().getStatus(),
                "the insert cannot have succeeded - the sequence was handing out a taken id");

        // The regression that cost the day: this came back as 409 "conflicts
        // with something that already exists", which sent the reader looking
        // for a duplicate product that did not exist. A generated-id collision
        // is a server fault and must say so.
        assertNotEquals(409, result.getResponse().getStatus(),
                "a primary-key collision on a generated id must not be reported as the caller's conflict");
        assertEquals(500, result.getResponse().getStatus());
        assertTrue(responseBody.contains("fault on our side"),
                "the message must not blame the admin's input; was: " + responseBody);
        assertFalse(responseBody.contains("already exists"),
                "the old misleading wording must be gone; was: " + responseBody);
    }

    @Test
    @WithStaff
    @DisplayName("the guard repairs the drift, and the same request then succeeds")
    void guardRepairsDriftAndCreationWorks() throws Exception {
        ensureAProductExists();
        windSequenceBackBelowTheTable();

        List<String> repaired = guard.resync();

        assertTrue(repaired.stream().anyMatch(s -> s.startsWith("products ")),
                "the guard must report products among the tables it repaired; reported: " + repaired);
        assertTrue(sequenceValue() >= maxProductId(),
                "after the repair the sequence must be at or ahead of the table");

        MvcResult result = postProduct("DriftTest Dhoop Batti");
        assertEquals(200, result.getResponse().getStatus(),
                "the exact request that failed before must now succeed; body: "
                        + result.getResponse().getContentAsString());
    }

    @Test
    @DisplayName("the guard only ever moves a sequence forward")
    void guardNeverMovesASequenceBackwards() {
        ensureAProductExists();
        long max = maxProductId();
        // Deliberately ahead of the table, which is a legitimate state - ids
        // are consumed by rolled-back transactions all the time.
        jdbc.queryForObject("SELECT setval('products_id_seq', ?, true)", Long.class, max + 1000);

        List<String> repaired = guard.resync();

        assertEquals(max + 1000, sequenceValue(),
                "a sequence ahead of its table must be left exactly where it is");
        assertTrue(repaired.stream().noneMatch(s -> s.startsWith("products ")),
                "nothing about products needed repair; reported: " + repaired);
    }

    @Test
    @DisplayName("the guard leaves Hibernate's block-allocated sequences alone")
    void guardIgnoresStandaloneSequences() {
        // order_items_seq (V10) and order_number_seq (V6) are handed out by
        // Hibernate in blocks and are SUPPOSED to run ahead of their tables.
        // They own no column, so pg_get_serial_sequence must not match them -
        // resetting one to max(id) would reissue ids Hibernate already holds.
        List<String> owned = jdbc.queryForList("""
                SELECT pg_get_serial_sequence(
                           quote_ident(c.table_schema) || '.' || quote_ident(c.table_name),
                           c.column_name) AS seq_name
                FROM information_schema.columns c
                WHERE c.table_schema = current_schema()
                  AND pg_get_serial_sequence(
                           quote_ident(c.table_schema) || '.' || quote_ident(c.table_name),
                           c.column_name) IS NOT NULL
                """, String.class);

        assertFalse(owned.stream().anyMatch(s -> s.endsWith("order_items_seq")),
                "order_items_seq is block-allocated by Hibernate and must never be re-synced");
        assertFalse(owned.stream().anyMatch(s -> s.endsWith("order_number_seq")),
                "order_number_seq is block-allocated by Hibernate and must never be re-synced");
        assertTrue(owned.stream().anyMatch(s -> s.endsWith("products_id_seq")),
                "products_id_seq is column-owned and must be covered");
    }

    @Test
    @DisplayName("a genuine unique conflict is still a 409, not swept into the server-fault branch")
    void genuineUniqueConflictIsStill409() throws Exception {
        // customers.email carries a real unique constraint. Two registrations
        // with the same address must still read as a conflict the caller can
        // act on - the new primary-key branch must not have swallowed them.
        String email = "drift-test-" + System.nanoTime() + "@example.com";
        String body = """
                {"fullName":"Drift Test","email":"%s","mobileNumber":"%d","password":"Passw0rd!23"}
                """.formatted(email, 9000000000L + (System.nanoTime() % 999999999L));

        mockMvc.perform(post("/api/auth/register").contentType("application/json").content(body));
        MvcResult duplicate = mockMvc.perform(
                post("/api/auth/register").contentType("application/json").content(body)).andReturn();

        int status = duplicate.getResponse().getStatus();
        assertTrue(status == 400 || status == 409,
                "a duplicate registration must be a client-side 4xx, not a server fault; was " + status
                        + " body: " + duplicate.getResponse().getContentAsString());
    }
}
