package com.gpstore.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

/**
 * Keeps every identity sequence at or ahead of the largest id in its table.
 *
 * V16 does this once, as a migration. This does it on every boot, because the
 * cause recurs and the symptom is severe out of all proportion to it.
 *
 * THE SYMPTOM. Admin "Add Product" answered 409 "That conflicts with something
 * that already exists" for every product, including names that collide with
 * nothing - there is no unique constraint on products.name. The conflict was
 * on products_pkey: the application asked for an id that a row already held.
 *
 * THE CAUSE. Hibernate's @GeneratedValue(IDENTITY) maps to
 * GENERATED BY DEFAULT AS IDENTITY, which permits an INSERT to supply its own
 * id - and when one does, the sequence behind the column is not advanced. A
 * restored dump, a CSV import, or one row typed into a SQL console leaves the
 * sequence permanently behind the table, and from then on every insert the
 * application makes collides. Nothing about that is visible from the admin
 * screen, and nothing about it heals on its own.
 *
 * So this is not a migration that can be considered done. Anyone with a SQL
 * console can recreate the condition in one statement, and the next person to
 * meet it sees only a conflict message about a product that does not exist.
 *
 * FORWARD ONLY, and that restriction is the whole safety argument: setval is
 * only ever called with a value larger than where the sequence already is.
 * Moving a sequence backwards would hand out ids that are already in use,
 * which is precisely the failure this exists to prevent.
 *
 * OWNED SEQUENCES ONLY. pg_get_serial_sequence matches only the sequence a
 * column owns. order_items_seq and order_number_seq are standalone, handed out
 * by Hibernate in blocks, and are supposed to run ahead of their tables; they
 * own no column, so they are never touched here.
 *
 * Runs on ApplicationReadyEvent rather than @PostConstruct so it cannot delay
 * or fail the context: a store that cannot re-sync a sequence should still
 * open. A failure here is logged and swallowed for the same reason.
 */
@Component
public class IdentitySequenceGuard {

    private static final Logger log = LoggerFactory.getLogger(IdentitySequenceGuard.class);

    /**
     * Every identity/serial column in the current schema, paired with the
     * sequence it owns and the largest id the table actually holds. The
     * COALESCE on pg_sequence_last_value covers a sequence that has never been
     * read from, which reports NULL rather than 0.
     */
    private static final String DRIFTED_SEQUENCES = """
            SELECT pg_get_serial_sequence(
                       quote_ident(c.table_schema) || '.' || quote_ident(c.table_name),
                       c.column_name) AS seq_name,
                   c.table_name,
                   c.column_name
            FROM information_schema.columns c
            WHERE c.table_schema = current_schema()
              AND pg_get_serial_sequence(
                       quote_ident(c.table_schema) || '.' || quote_ident(c.table_name),
                       c.column_name) IS NOT NULL
            """;

    private final JdbcTemplate jdbc;
    private final boolean enabled;

    public IdentitySequenceGuard(JdbcTemplate jdbc,
                                 @Value("${app.identity-sequence-guard.enabled:true}") boolean enabled) {
        this.jdbc = jdbc;
        this.enabled = enabled;
    }

    @EventListener(ApplicationReadyEvent.class)
    public void resyncOnStartup() {
        if (!enabled) {
            return;
        }
        try {
            List<String> repaired = resync();
            if (!repaired.isEmpty()) {
                log.warn("Identity sequence drift found and repaired on {} table(s): {}. A sequence falls behind its "
                        + "table when rows are inserted with explicit ids - a restored dump, a CSV import, or an "
                        + "INSERT typed into a SQL console. Until repaired, every insert the application makes into "
                        + "these tables fails with a primary-key conflict. See V16__resync_identity_sequences.sql.",
                        repaired.size(), repaired);
            }
        } catch (Exception e) {
            // Never take the store down over this. Worst case the drift stays
            // and the (now accurate) error message says so.
            log.error("Identity sequence check failed; skipping. Sequences were NOT verified this boot.", e);
        }
    }

    /**
     * Re-syncs every column-owned sequence and returns the tables whose
     * sequence had to be moved forward. Public so it can be driven directly -
     * by a test, or by an operator who has just restored a dump and does not
     * want to wait for a restart.
     */
    public List<String> resync() {
        List<String> repaired = new ArrayList<>();

        for (var row : jdbc.queryForList(DRIFTED_SEQUENCES)) {
            String seqName = (String) row.get("seq_name");
            String table = (String) row.get("table_name");
            String column = (String) row.get("column_name");

            // Identifiers come from information_schema, not from a request -
            // they are the database's own catalogue, and quote_ident above
            // already produced the qualified name for the sequence.
            Long maxId = jdbc.queryForObject(
                    "SELECT COALESCE(max(" + quoteIdent(column) + "), 0) FROM " + quoteIdent(table), Long.class);
            Long seqValue = jdbc.queryForObject(
                    "SELECT COALESCE(pg_sequence_last_value(?::regclass), 0)", Long.class, seqName);

            if (maxId != null && seqValue != null && maxId > seqValue) {
                jdbc.queryForObject("SELECT setval(?::regclass, ?, true)", Long.class, seqName, maxId);
                repaired.add(table + " (" + seqValue + " -> " + maxId + ")");
            }
        }
        return repaired;
    }

    /**
     * Postgres identifier quoting. These names come from information_schema
     * rather than from user input, so this guards against an awkward column
     * name rather than against injection - but a name is still never
     * concatenated in raw.
     */
    private static String quoteIdent(String identifier) {
        return '"' + identifier.replace("\"", "\"\"") + '"';
    }
}
