package com.gpstore.marketplace;

import java.util.List;

/**
 * A hundred businesses that have nothing in common but a platform.
 *
 * <h2>Why the variety is the point</h2>
 *
 * <p>A hundred copies of one kirana would prove nothing: every query would be
 * shaped the same, every category would be the same word, and the one thing
 * worth testing - that a phone shop, a saree shop, a tractor-parts dealer and
 * a biryani counter can share one database without seeing each other - would
 * be invisible.
 *
 * <p>So each trade here brings its OWN attribute vocabulary. A phone is told
 * apart by Brand, Model, RAM, Storage and Colour; a saree by Material, Colour,
 * Design, Length and Occasion; a car part by Manufacturer, Compatible model
 * and Part number; a pizza by Size, Crust and Add-ons; a fertilizer by Grade
 * and Form. That is the generic variant model (V71) being made to earn its
 * keep across a hundred trades at once: if any of this had to become a column,
 * the schema would need a migration per trade, and the next trade after that.
 *
 * <p>Sizes vary too, because a marketplace is not uniform. A kirana carries
 * five hundred lines; a jeweller carries a dozen; a pizza counter carries
 * fifteen. Code that only works when every shop is the same size fails on the
 * first real one.
 *
 * <p>EVERY NAME SAYS TEST. Not decoration - these rows must be unmistakable if
 * one is ever seen on a screen, and greppable if one is ever seen in a
 * database.
 *
 * <p>GENERATED SHAPE, HAND-WRITTEN CONTENT. The list is long because a hundred
 * trades is a hundred trades; each entry's categories, attribute names and
 * product stems were chosen for that trade rather than copied from the one
 * above it.
 */
enum Trade {
    KIRANA("Grocery / Kirana", Size.HUGE,
            List.of("Atta, Rice & Dal", "Oil & Ghee", "Masala & Spices", "Biscuits & Snacks", "Tea, Coffee & Beverages", "Cleaning & Household"),
            List.of("Pack size", "Unit"),
            List.of("Aashirvaad Atta", "India Gate Basmati", "Toor Dal", "Fortune Oil", "Tata Salt", "Everest Garam Masala", "Parle-G", "Red Label Tea", "Surf Excel", "Maggi Noodles", "Amul Butter", "Saffola Oil"),
            List.of("500 g", "1 kg", "5 kg", "250 g", "2 L", "kg", "g", "L")),
    SUPERMARKET("Supermarket", Size.HUGE,
            List.of("Staples", "Packaged Foods", "Frozen", "Household", "Personal Care", "Baby"),
            List.of("Pack size", "Unit", "Brand"),
            List.of("Corn Flakes", "Frozen Peas", "Dish Wash Gel", "Toilet Cleaner", "Shampoo Sachet", "Diaper Pack", "Cooking Oil Jar"),
            List.of("500 g", "1 kg", "2 kg", "1 L", "5 L", "Brand A", "Brand B")),
    FRUITS("Fruits", Size.MEDIUM,
            List.of("Seasonal Fruits", "Exotic Fruits", "Cut Fruits"),
            List.of("Weight", "Grade", "Origin"),
            List.of("Banana Robusta", "Apple Shimla", "Mango Dasheri", "Papaya", "Pomegranate", "Grapes Green"),
            List.of("500 g", "1 kg", "2 kg", "A", "B", "Local", "Imported")),
    VEGETABLES("Vegetables", Size.MEDIUM,
            List.of("Daily Vegetables", "Leafy Greens", "Exotic Vegetables"),
            List.of("Weight", "Grade"),
            List.of("Tomato", "Onion", "Potato", "Spinach", "Coriander", "Cauliflower", "Brinjal"),
            List.of("250 g", "500 g", "1 kg", "A", "B")),
    DAIRY("Dairy", Size.SMALL,
            List.of("Milk", "Curd & Paneer", "Butter & Cheese", "Sweets"),
            List.of("Volume", "Type"),
            List.of("Toned Milk", "Full Cream Milk", "Fresh Curd", "Paneer Block", "Cheese Slices", "Lassi"),
            List.of("200 ml", "500 ml", "1 L", "200 g", "400 g", "Toned", "Full cream")),
    BAKERY("Bakery", Size.SMALL,
            List.of("Cakes", "Pastries", "Breads", "Cookies"),
            List.of("Weight", "Flavour", "Eggless"),
            List.of("Chocolate Truffle Cake", "Black Forest Pastry", "Brown Bread", "Butter Cookies", "Croissant"),
            List.of("500 g", "1 kg", "Chocolate", "Vanilla", "Strawberry", "Yes", "No")),
    SWEETS("Sweets", Size.SMALL,
            List.of("Milk Sweets", "Dry Sweets", "Bengali Sweets", "Festive Boxes"),
            List.of("Weight", "Sweetness", "Shelf life"),
            List.of("Kaju Katli", "Gulab Jamun", "Rasgulla", "Soan Papdi", "Motichoor Laddu"),
            List.of("250 g", "500 g", "1 kg", "Regular", "Less sugar", "3 days", "15 days")),
    SNACKS("Snacks", Size.MEDIUM,
            List.of("Namkeen", "Chips", "Dry Snacks", "Sweet Snacks"),
            List.of("Pack size", "Flavour"),
            List.of("Aloo Bhujia", "Salted Chips", "Masala Peanuts", "Mixture", "Khakhra"),
            List.of("50 g", "100 g", "200 g", "400 g", "Masala", "Salted", "Tangy")),
    BEVERAGES("Beverages", Size.MEDIUM,
            List.of("Soft Drinks", "Juices", "Energy Drinks", "Water"),
            List.of("Volume", "Flavour", "Sugar"),
            List.of("Cola Bottle", "Orange Juice", "Energy Drink Can", "Mineral Water", "Lemon Soda"),
            List.of("250 ml", "500 ml", "1 L", "2 L", "Orange", "Mixed fruit", "Regular", "Diet")),
    DRY_FRUITS("Dry fruits", Size.SMALL,
            List.of("Nuts", "Dried Fruits", "Seeds", "Gift Packs"),
            List.of("Weight", "Grade", "Origin"),
            List.of("Almond", "Cashew", "Raisin", "Pistachio", "Walnut Kernel", "Fig"),
            List.of("100 g", "250 g", "500 g", "1 kg", "W240", "W320", "Local", "Imported")),
    ORGANIC("Organic foods", Size.SMALL,
            List.of("Organic Staples", "Organic Spices", "Cold Pressed Oils", "Superfoods"),
            List.of("Weight", "Certification"),
            List.of("Organic Wheat Flour", "Organic Turmeric", "Cold Pressed Mustard Oil", "Quinoa", "Jaggery Powder"),
            List.of("500 g", "1 kg", "2 kg", "India Organic", "Jaivik Bharat")),
    MEAT("Meat", Size.SMALL,
            List.of("Chicken", "Mutton", "Cold Cuts", "Marinated"),
            List.of("Weight", "Cut", "Bone"),
            List.of("Chicken Curry Cut", "Chicken Breast", "Mutton Curry Cut", "Chicken Sausage", "Keema"),
            List.of("250 g", "500 g", "1 kg", "Curry cut", "Boneless", "With bone")),
    SEAFOOD("Fish / seafood", Size.SMALL,
            List.of("Fresh Fish", "Prawns", "Dried Fish", "Ready to Cook"),
            List.of("Weight", "Cut", "Freshness"),
            List.of("Rohu Fish", "Katla Fish", "Prawns Medium", "Pomfret", "Dried Bombil"),
            List.of("250 g", "500 g", "1 kg", "Whole", "Steaks", "Fresh", "Frozen")),
    PHONES("Mobile phones", Size.SMALL,
            List.of("Smartphones", "Feature Phones", "Tablets", "Refurbished"),
            List.of("Brand", "Model", "RAM", "Storage", "Colour"),
            List.of("Moto Edge", "Galaxy A", "Pixel", "Redmi Note", "iQOO Z", "Realme Narzo", "Nokia Classic"),
            List.of("Motorola", "Samsung", "Google", "Xiaomi", "8 GB", "12 GB", "128 GB", "256 GB", "Black", "Red", "Blue")),
    PHONE_ACCESSORIES("Mobile accessories", Size.MEDIUM,
            List.of("Chargers", "Cases & Covers", "Screen Guards", "Earphones", "Power Banks"),
            List.of("Compatibility", "Colour", "Length", "Output"),
            List.of("USB-C Charger", "Silicone Back Cover", "Tempered Glass", "Wired Earphones", "Power Bank", "Car Mount"),
            List.of("Universal", "Type-C", "Lightning", "Black", "Clear", "1 m", "2 m", "18 W", "65 W")),
    COMPUTERS("Computers", Size.SMALL,
            List.of("Laptops", "Desktops", "Monitors", "All-in-One"),
            List.of("Brand", "Processor", "RAM", "Storage", "Screen size"),
            List.of("Business Laptop", "Gaming Laptop", "Desktop Tower", "Office Monitor"),
            List.of("Lenovo", "HP", "Dell", "i3", "i5", "i7", "Ryzen 5", "8 GB", "16 GB", "512 GB SSD", "1 TB HDD", "14 inch", "15.6 inch")),
    COMPUTER_ACCESSORIES("Computer accessories", Size.MEDIUM,
            List.of("Keyboards & Mice", "Storage", "Networking", "Cables", "Printers"),
            List.of("Capacity", "Interface", "Colour"),
            List.of("Wireless Mouse", "Mechanical Keyboard", "Portable SSD", "USB Hub", "HDMI Cable", "Wi-Fi Router", "Laser Printer"),
            List.of("256 GB", "512 GB", "1 TB", "USB 3.0", "Type-C", "Bluetooth", "Black", "White")),
    CONSUMER_ELECTRONICS("Consumer electronics", Size.MEDIUM,
            List.of("Televisions", "Audio", "Cameras", "Smart Devices"),
            List.of("Brand", "Model", "Screen size", "Connectivity"),
            List.of("LED Television", "Soundbar", "Bluetooth Speaker", "Action Camera", "Smart Bulb"),
            List.of("Sony", "LG", "Samsung", "32 inch", "43 inch", "55 inch", "Bluetooth", "Wi-Fi", "HDMI")),
    HOME_APPLIANCES("Home appliances", Size.SMALL,
            List.of("Kitchen Appliances", "Cooling", "Cleaning", "Water"),
            List.of("Brand", "Capacity", "Power", "Colour"),
            List.of("Mixer Grinder", "Induction Cooktop", "Table Fan", "Washing Machine", "Electric Kettle", "Microwave Oven"),
            List.of("Bajaj", "Philips", "1.5 L", "2 L", "6 kg", "750 W", "1200 W", "2000 W", "Grey", "White")),
    ELECTRICAL("Electrical supplies", Size.MEDIUM,
            List.of("Wires & Cables", "Switches", "Lighting", "Fans", "MCB & Distribution"),
            List.of("Rating", "Colour", "Length", "Material"),
            List.of("House Wire", "Modular Switch", "LED Bulb", "Ceiling Fan", "MCB", "Extension Board"),
            List.of("6 A", "16 A", "32 A", "9 W", "12 W", "90 m", "Red", "White", "Copper")),
    SAREE("Sarees", Size.MEDIUM,
            List.of("Silk Sarees", "Cotton Sarees", "Georgette Sarees", "Bridal"),
            List.of("Material", "Colour", "Design", "Length", "Occasion"),
            List.of("Banarasi Silk Saree", "Kanjivaram Saree", "Chanderi Cotton Saree", "Georgette Printed Saree", "Tussar Silk Saree"),
            List.of("Silk", "Cotton", "Georgette", "Red", "Green", "Maroon", "Printed", "Woven", "5.5 m", "6.3 m", "Wedding", "Daily")),
    MENSWEAR("Men's clothing", Size.MEDIUM,
            List.of("Shirts", "Trousers", "T-Shirts", "Kurta", "Jeans"),
            List.of("Brand", "Size", "Colour", "Material", "Gender"),
            List.of("Formal Shirt", "Slim Fit Trousers", "Round Neck T-Shirt", "Cotton Kurta", "Denim Jeans"),
            List.of("Peter England", "Levis", "S", "M", "L", "XL", "XXL", "Blue", "White", "Cotton", "Denim", "Men")),
    WOMENSWEAR("Women's clothing", Size.MEDIUM,
            List.of("Kurtis", "Leggings", "Dresses", "Tops", "Dupattas"),
            List.of("Brand", "Size", "Colour", "Material", "Gender"),
            List.of("Anarkali Kurti", "Ankle Leggings", "A-Line Dress", "Crop Top", "Chiffon Dupatta"),
            List.of("Biba", "W", "S", "M", "L", "XL", "Pink", "Black", "Rayon", "Cotton", "Women")),
    KIDSWEAR("Kids clothing", Size.SMALL,
            List.of("Boys", "Girls", "Infants", "School Wear"),
            List.of("Age", "Size", "Colour", "Gender"),
            List.of("Boys T-Shirt", "Girls Frock", "Infant Romper", "School Shirt"),
            List.of("2-3 y", "4-5 y", "6-7 y", "S", "M", "L", "Blue", "Pink", "Boys", "Girls")),
    ETHNIC("Ethnic wear", Size.MEDIUM,
            List.of("Lehenga", "Sherwani", "Salwar Suit", "Dhoti"),
            List.of("Material", "Colour", "Size", "Occasion"),
            List.of("Bridal Lehenga", "Silk Sherwani", "Cotton Salwar Suit", "Pure Dhoti"),
            List.of("Silk", "Velvet", "Cotton", "Red", "Cream", "M", "L", "XL", "Wedding", "Festive")),
    FOOTWEAR("Footwear", Size.MEDIUM,
            List.of("Formal Shoes", "Sandals", "Slippers", "Casual"),
            List.of("Brand", "Size", "Colour", "Style", "Material"),
            List.of("Leather Oxford", "Floater Sandal", "Rubber Slipper", "Canvas Casual"),
            List.of("Bata", "Paragon", "6", "7", "8", "9", "10", "Black", "Brown", "Lace-up", "Slip-on", "Leather")),
    SPORTS_SHOES("Sports shoes", Size.SMALL,
            List.of("Running", "Training", "Trekking", "Football"),
            List.of("Brand", "Size", "Colour", "Style"),
            List.of("Running Shoes", "Training Shoes", "Trekking Boots", "Football Studs"),
            List.of("Nike", "Adidas", "Puma", "7", "8", "9", "10", "11", "Black", "White", "Blue", "Lace-up")),
    BAGS("Bags / luggage", Size.SMALL,
            List.of("Backpacks", "Trolley Bags", "Handbags", "Laptop Bags"),
            List.of("Brand", "Capacity", "Colour", "Material"),
            List.of("School Backpack", "Cabin Trolley", "Ladies Handbag", "Laptop Backpack"),
            List.of("American Tourister", "Skybags", "20 L", "30 L", "55 cm", "Black", "Blue", "Polyester")),
    FASHION_ACCESSORIES("Fashion accessories", Size.SMALL,
            List.of("Belts", "Wallets", "Scarves", "Hair Accessories"),
            List.of("Material", "Colour", "Size"),
            List.of("Leather Belt", "Mens Wallet", "Silk Scarf", "Hair Clip Set"),
            List.of("Leather", "Synthetic", "Black", "Brown", "Free size", "32", "34")),
    JEWELLERY("Jewellery", Size.MICRO,
            List.of("Earrings", "Bangles", "Necklaces", "Rings"),
            List.of("Material", "Colour", "Size", "Purity"),
            List.of("Oxidised Earrings", "Glass Bangles Set", "Pendant Chain", "Finger Ring"),
            List.of("Oxidised", "Gold plated", "Silver", "2.4", "2.6", "Gold", "Silver", "92.5")),
    COSMETICS("Cosmetics", Size.MEDIUM,
            List.of("Face", "Lips", "Eyes", "Nails"),
            List.of("Shade", "Volume", "Skin type", "Finish"),
            List.of("Foundation", "Lipstick", "Kajal", "Nail Polish", "Compact Powder"),
            List.of("Ivory", "Beige", "Maroon", "Nude", "30 ml", "100 ml", "Oily", "Dry", "Matte", "Glossy")),
    BEAUTY("Beauty products", Size.MEDIUM,
            List.of("Skin Care", "Hair Care", "Body Care", "Fragrance"),
            List.of("Volume", "Skin type", "Fragrance"),
            List.of("Face Wash", "Hair Oil", "Body Lotion", "Deodorant", "Face Serum"),
            List.of("100 ml", "200 ml", "400 ml", "Oily", "Dry", "Normal", "Floral", "Citrus")),
    PERSONAL_CARE("Personal care", Size.MEDIUM,
            List.of("Oral Care", "Bath", "Shaving", "Feminine Care"),
            List.of("Pack size", "Variant"),
            List.of("Toothpaste", "Bathing Soap", "Shaving Cream", "Sanitary Pads", "Hand Wash"),
            List.of("100 g", "150 g", "250 ml", "Pack of 3", "Regular", "Sensitive")),
    SALON("Salon supplies", Size.SMALL,
            List.of("Hair Colour", "Salon Tools", "Spa", "Consumables"),
            List.of("Volume", "Shade", "Professional"),
            List.of("Hair Colour Tube", "Professional Dryer", "Spa Cream", "Salon Towel"),
            List.of("60 ml", "100 ml", "Brown", "Burgundy", "Yes", "No")),
    PHARMACY("Pharmacy", Size.LARGE,
            List.of("Pain Relief", "Cold & Fever", "Diabetes Care", "Vitamins", "First Aid"),
            List.of("Strength", "Pack", "Form"),
            List.of("Paracetamol", "Cetirizine", "Metformin", "Vitamin D3", "Antiseptic Liquid", "ORS Sachet"),
            List.of("500 mg", "650 mg", "10 mg", "10 tablets", "15 tablets", "100 ml", "Tablet", "Syrup")),
    MEDICAL_SUPPLIES("Medical supplies", Size.MEDIUM,
            List.of("Diagnostics", "Mobility", "Consumables", "Equipment"),
            List.of("Size", "Material", "Accuracy"),
            List.of("Digital Thermometer", "BP Monitor", "Wheelchair", "Surgical Gloves", "Nebuliser"),
            List.of("S", "M", "L", "Latex", "Nitrile", "Steel", "+/- 0.1")),
    OPTICAL("Optical / eyewear", Size.SMALL,
            List.of("Spectacles", "Sunglasses", "Contact Lenses", "Frames"),
            List.of("Frame size", "Colour", "Lens type", "Power"),
            List.of("Rectangle Frame", "Aviator Sunglasses", "Monthly Contact Lens", "Reading Glasses"),
            List.of("Small", "Medium", "Large", "Black", "Gold", "Anti-glare", "Blue cut", "-1.0", "+1.5")),
    HEALTH("Health products", Size.MEDIUM,
            List.of("Supplements", "Ayurveda", "Fitness Nutrition", "Immunity"),
            List.of("Weight", "Flavour", "Form"),
            List.of("Whey Protein", "Chyawanprash", "Multivitamin", "Protein Bar", "Immunity Kadha"),
            List.of("500 g", "1 kg", "250 g", "Chocolate", "Unflavoured", "Powder", "Tablet")),
    RESTAURANT("Restaurant", Size.SMALL,
            List.of("Starters", "Main Course", "Breads", "Rice", "Desserts"),
            List.of("Portion size", "Veg/Non-veg", "Spice level", "Add-ons"),
            List.of("Paneer Tikka", "Dal Makhani", "Butter Naan", "Jeera Rice", "Gulab Jamun"),
            List.of("Half", "Full", "Regular", "Large", "Veg", "Non-veg", "Mild", "Medium", "Spicy", "Extra cheese")),
    BIRYANI("Biryani restaurant", Size.MICRO,
            List.of("Biryani", "Kebabs", "Breads", "Beverages"),
            List.of("Portion size", "Veg/Non-veg", "Spice level"),
            List.of("Chicken Biryani", "Mutton Biryani", "Veg Biryani", "Seekh Kebab"),
            List.of("Half", "Full", "Family pack", "Veg", "Non-veg", "Mild", "Spicy")),
    FAST_FOOD("Fast food", Size.MICRO,
            List.of("Burgers", "Rolls", "Fries", "Combos"),
            List.of("Portion size", "Veg/Non-veg", "Add-ons"),
            List.of("Veg Burger", "Chicken Roll", "French Fries", "Combo Meal"),
            List.of("Regular", "Medium", "Large", "Veg", "Non-veg", "Extra cheese", "Extra mayo")),
    PIZZA("Pizza", Size.MICRO,
            List.of("Veg Pizza", "Non-veg Pizza", "Sides", "Beverages"),
            List.of("Size", "Crust", "Veg/Non-veg", "Add-ons"),
            List.of("Margherita Pizza", "Farmhouse Pizza", "Chicken Tikka Pizza", "Garlic Bread"),
            List.of("Regular", "Medium", "Large", "Thin crust", "Cheese burst", "Veg", "Non-veg", "Extra cheese")),
    CAFE("Cafe", Size.MICRO,
            List.of("Coffee", "Tea", "Bakes", "Sandwiches"),
            List.of("Portion size", "Milk", "Sugar"),
            List.of("Cappuccino", "Cold Coffee", "Masala Chai", "Veg Sandwich", "Brownie"),
            List.of("Small", "Regular", "Large", "Full cream", "Skimmed", "No sugar", "Regular")),
    TEA_SHOP("Tea shop", Size.MICRO,
            List.of("Tea", "Snacks", "Biscuits"),
            List.of("Portion size", "Sugar"),
            List.of("Masala Chai", "Ginger Tea", "Samosa", "Bun Maska"),
            List.of("Small", "Regular", "Large", "No sugar", "Less sugar", "Regular")),
    JUICE("Juice shop", Size.MICRO,
            List.of("Fresh Juices", "Shakes", "Smoothies"),
            List.of("Volume", "Sugar", "Ice"),
            List.of("Orange Juice", "Mango Shake", "Banana Smoothie", "Sugarcane Juice"),
            List.of("250 ml", "350 ml", "500 ml", "No sugar", "Regular", "With ice", "No ice")),
    ICE_CREAM("Ice cream", Size.MICRO,
            List.of("Cones", "Tubs", "Sticks", "Sundaes"),
            List.of("Volume", "Flavour"),
            List.of("Vanilla Tub", "Chocolate Cone", "Kulfi Stick", "Fruit Sundae"),
            List.of("100 ml", "500 ml", "1 L", "Vanilla", "Chocolate", "Butterscotch", "Mango")),
    STREET_FOOD("Street food", Size.MICRO,
            List.of("Chaat", "Tikki", "Pav", "Fried"),
            List.of("Portion size", "Spice level"),
            List.of("Pani Puri", "Aloo Tikki", "Vada Pav", "Samosa Chaat"),
            List.of("Half plate", "Full plate", "Mild", "Medium", "Spicy")),
    SOUTH_INDIAN("South Indian restaurant", Size.SMALL,
            List.of("Dosa", "Idli & Vada", "Rice", "Beverages"),
            List.of("Portion size", "Veg/Non-veg", "Spice level"),
            List.of("Masala Dosa", "Plain Idli", "Medu Vada", "Curd Rice", "Filter Coffee"),
            List.of("Half", "Full", "Regular", "Veg", "Mild", "Medium")),
    NORTH_INDIAN("North Indian restaurant", Size.SMALL,
            List.of("Curries", "Breads", "Rice", "Starters"),
            List.of("Portion size", "Veg/Non-veg", "Spice level"),
            List.of("Shahi Paneer", "Butter Chicken", "Tandoori Roti", "Veg Pulao"),
            List.of("Half", "Full", "Veg", "Non-veg", "Mild", "Medium", "Spicy")),
    CHINESE("Chinese restaurant", Size.SMALL,
            List.of("Noodles", "Rice", "Starters", "Soups"),
            List.of("Portion size", "Veg/Non-veg", "Spice level"),
            List.of("Hakka Noodles", "Fried Rice", "Chilli Paneer", "Manchow Soup"),
            List.of("Half", "Full", "Veg", "Non-veg", "Mild", "Spicy")),
    HARDWARE("Hardware", Size.LARGE,
            List.of("Hand Tools", "Fasteners", "Plumbing", "Adhesives"),
            List.of("Size", "Material", "Grade", "Dimensions"),
            List.of("Claw Hammer", "Screwdriver Set", "Hex Bolt", "PVC Pipe", "Sealant Tube"),
            List.of("6 mm", "8 mm", "12 mm", "Steel", "Brass", "PVC", "Grade A", "Grade B", "1/2 inch")),
    BUILDING_MATERIALS("Building materials", Size.LARGE,
            List.of("Cement", "Steel", "Bricks", "Aggregates"),
            List.of("Grade", "Weight", "Dimensions"),
            List.of("OPC Cement Bag", "TMT Bar", "Red Brick", "River Sand"),
            List.of("43 grade", "53 grade", "50 kg", "8 mm", "12 mm", "16 mm", "230x110x75 mm")),
    PLUMBING("Plumbing", Size.MEDIUM,
            List.of("Pipes", "Fittings", "Taps", "Tanks"),
            List.of("Size", "Material", "Dimensions"),
            List.of("CPVC Pipe", "Elbow Joint", "Pillar Cock", "Water Tank"),
            List.of("1/2 inch", "3/4 inch", "1 inch", "CPVC", "Brass", "500 L", "1000 L")),
    PAINT("Paint", Size.MEDIUM,
            List.of("Interior", "Exterior", "Enamel", "Primer"),
            List.of("Volume", "Shade", "Finish"),
            List.of("Interior Emulsion", "Exterior Emulsion", "Enamel Paint", "Wall Primer"),
            List.of("1 L", "4 L", "10 L", "20 L", "White", "Ivory", "Matte", "Glossy")),
    TILES("Tiles", Size.MEDIUM,
            List.of("Floor Tiles", "Wall Tiles", "Vitrified", "Outdoor"),
            List.of("Dimensions", "Finish", "Material"),
            List.of("Vitrified Floor Tile", "Ceramic Wall Tile", "Anti-skid Tile", "Wooden Finish Tile"),
            List.of("600x600 mm", "300x600 mm", "800x800 mm", "Glossy", "Matte", "Ceramic", "Vitrified")),
    SANITARY("Sanitary ware", Size.MEDIUM,
            List.of("Wash Basins", "Closets", "Showers", "Accessories"),
            List.of("Dimensions", "Colour", "Material"),
            List.of("Wall Hung Basin", "One Piece Closet", "Overhead Shower", "Towel Rod"),
            List.of("450 mm", "600 mm", "White", "Ivory", "Ceramic", "Steel")),
    TOOLS("Tools", Size.MEDIUM,
            List.of("Power Tools", "Measuring", "Cutting", "Safety"),
            List.of("Power", "Size", "Material"),
            List.of("Angle Grinder", "Cordless Drill", "Measuring Tape", "Safety Helmet"),
            List.of("500 W", "750 W", "1200 W", "4 inch", "5 m", "10 m", "Steel", "ABS")),
    FURNITURE("Furniture", Size.SMALL,
            List.of("Seating", "Tables", "Storage", "Beds"),
            List.of("Material", "Dimensions", "Finish", "Seats"),
            List.of("Plastic Chair", "Study Table", "Steel Almirah", "Single Bed", "Shoe Rack"),
            List.of("Plastic", "Engineered wood", "Steel", "120x60 cm", "180x90 cm", "Walnut", "Teak", "1", "2")),
    HOME_DECOR("Home decor", Size.SMALL,
            List.of("Wall Decor", "Vases", "Showpieces", "Clocks"),
            List.of("Material", "Colour", "Dimensions"),
            List.of("Wall Painting", "Ceramic Vase", "Brass Showpiece", "Wall Clock"),
            List.of("Wood", "Ceramic", "Brass", "Gold", "Multicolour", "30 cm", "45 cm")),
    KITCHENWARE("Kitchenware", Size.MEDIUM,
            List.of("Cookware", "Storage", "Dining", "Tools"),
            List.of("Capacity", "Material", "Colour"),
            List.of("Pressure Cooker", "Steel Container Set", "Dinner Plate", "Chopping Board"),
            List.of("2 L", "3 L", "5 L", "Steel", "Aluminium", "Non-stick", "Silver")),
    MATTRESS("Mattress / bedding", Size.SMALL,
            List.of("Mattresses", "Pillows", "Bedsheets", "Comforters"),
            List.of("Dimensions", "Material", "Thickness"),
            List.of("Foam Mattress", "Fibre Pillow", "Cotton Bedsheet", "Winter Comforter"),
            List.of("72x36 inch", "78x60 inch", "Foam", "Coir", "Cotton", "4 inch", "6 inch")),
    FURNISHING("Curtains / furnishing", Size.SMALL,
            List.of("Curtains", "Cushions", "Carpets", "Blinds"),
            List.of("Dimensions", "Material", "Colour"),
            List.of("Door Curtain", "Cushion Cover", "Floor Carpet", "Window Blind"),
            List.of("5 ft", "7 ft", "9 ft", "Polyester", "Cotton", "Maroon", "Beige")),
    STATIONERY("Stationery", Size.LARGE,
            List.of("Notebooks", "Pens & Pencils", "Files & Folders", "Art Supplies"),
            List.of("Size", "Colour", "Pages"),
            List.of("Long Notebook", "Gel Pen", "Ball Pen", "Box File", "Colour Pencils"),
            List.of("A4", "A5", "Blue", "Black", "Red", "172 pages", "300 pages")),
    BOOKS("Books", Size.LARGE,
            List.of("School Books", "Competitive Exams", "Fiction", "Children"),
            List.of("Language", "Binding", "Class", "Author"),
            List.of("Mathematics Textbook", "GK Guide", "Hindi Novel", "Picture Book"),
            List.of("Hindi", "English", "Paperback", "Hardbound", "Class 8", "Class 10", "Class 12")),
    SCHOOL_SUPPLIES("School supplies", Size.MEDIUM,
            List.of("Bags", "Geometry", "Lunch Boxes", "Uniform Accessories"),
            List.of("Size", "Colour", "Class"),
            List.of("School Bag", "Geometry Box", "Lunch Box", "Water Bottle"),
            List.of("Small", "Medium", "Large", "Blue", "Red", "Class 1-5", "Class 6-10")),
    OFFICE_SUPPLIES("Office supplies", Size.MEDIUM,
            List.of("Paper", "Filing", "Desk", "Presentation"),
            List.of("Size", "Pack size", "GSM"),
            List.of("A4 Paper Ream", "Box File", "Stapler", "White Board"),
            List.of("A4", "A3", "500 sheets", "Pack of 10", "70 GSM", "75 GSM")),
    PRINTING("Printing supplies", Size.MEDIUM,
            List.of("Cartridges", "Toners", "Paper", "Ribbons"),
            List.of("Compatibility", "Colour", "Yield"),
            List.of("Ink Cartridge", "Laser Toner", "Photo Paper", "Printer Ribbon"),
            List.of("HP 680", "Canon 810", "Black", "Tri-colour", "1500 pages", "2000 pages")),
    TOYS("Toys", Size.MEDIUM,
            List.of("Soft Toys", "Board Games", "Remote Control", "Educational"),
            List.of("Age", "Colour", "Material"),
            List.of("Teddy Bear", "Ludo Board", "RC Car", "Building Blocks", "Puzzle Set"),
            List.of("0-2 y", "3+", "6+", "8+", "Brown", "Red", "Plastic", "Plush")),
    BABY("Baby products", Size.MEDIUM,
            List.of("Diapers", "Feeding", "Bath", "Baby Food"),
            List.of("Size", "Age", "Pack size"),
            List.of("Baby Diapers", "Feeding Bottle", "Baby Soap", "Cereal Pack"),
            List.of("S", "M", "L", "XL", "0-6 m", "6-12 m", "Pack of 20", "Pack of 48")),
    GIFTS("Gifts", Size.MICRO,
            List.of("Gift Hampers", "Greeting Cards", "Personalised", "Festive"),
            List.of("Occasion", "Size", "Colour"),
            List.of("Chocolate Hamper", "Birthday Card", "Photo Mug", "Rakhi Set"),
            List.of("Birthday", "Anniversary", "Diwali", "Small", "Large", "Red", "Assorted")),
    PARTY("Party supplies", Size.MICRO,
            List.of("Decorations", "Balloons", "Tableware", "Costumes"),
            List.of("Colour", "Pack size", "Theme"),
            List.of("Party Balloons", "Birthday Banner", "Paper Plates", "Party Hat"),
            List.of("Red", "Blue", "Multicolour", "Pack of 10", "Pack of 50", "Cartoon", "Neon")),
    SPORTS_GOODS("Sports goods", Size.MEDIUM,
            List.of("Cricket", "Badminton", "Football", "Carrom"),
            List.of("Size", "Weight", "Material"),
            List.of("Cricket Bat", "Leather Ball", "Badminton Racket", "Football", "Carrom Board"),
            List.of("SH", "Full", "Size 5", "2 kg", "Willow", "Rubber", "Wood")),
    FITNESS("Fitness equipment", Size.SMALL,
            List.of("Weights", "Cardio", "Yoga", "Accessories"),
            List.of("Weight", "Material", "Dimensions"),
            List.of("Dumbbell Set", "Skipping Rope", "Yoga Mat", "Resistance Band"),
            List.of("2 kg", "5 kg", "10 kg", "Rubber", "PVC", "6 mm", "183x61 cm")),
    BICYCLE("Bicycle", Size.SMALL,
            List.of("Kids Cycles", "Geared", "Non-geared", "Electric"),
            List.of("Frame size", "Wheel size", "Colour", "Gears"),
            List.of("Kids Bicycle", "Mountain Bike", "City Cycle", "Electric Cycle"),
            List.of("14 inch", "16 inch", "26 inch", "29 inch", "Red", "Black", "Single speed", "21 speed")),
    BICYCLE_PARTS("Bicycle parts", Size.MEDIUM,
            List.of("Tyres", "Brakes", "Drivetrain", "Accessories"),
            List.of("Compatible model", "Size", "Material"),
            List.of("Bicycle Tyre", "Brake Cable", "Bicycle Chain", "Cycle Bell"),
            List.of("26 inch", "27.5 inch", "Universal", "Rubber", "Steel")),
    MOTORCYCLE_PARTS("Motorcycle parts", Size.LARGE,
            List.of("Engine", "Brakes & Clutch", "Filters", "Electricals"),
            List.of("Manufacturer", "Compatible model", "Part number", "Specification"),
            List.of("Brake Shoe Set", "Clutch Plate", "Oil Filter", "Spark Plug", "Chain Sprocket Kit"),
            List.of("Hero", "Honda", "Bajaj", "Splendor", "Activa", "Pulsar", "GP-TEST-PN-1", "GP-TEST-PN-2", "OEM")),
    CAR_PARTS("Car parts", Size.LARGE,
            List.of("Engine", "Suspension", "Filters", "Lighting"),
            List.of("Manufacturer", "Compatible model", "Part number", "Specification"),
            List.of("Air Filter", "Brake Pad Set", "Shock Absorber", "Headlight Assembly", "Wiper Blade"),
            List.of("Maruti", "Hyundai", "Tata", "Alto", "Swift", "i20", "GP-TEST-PN-3", "GP-TEST-PN-4", "OEM")),
    CAR_ACCESSORIES("Car accessories", Size.MEDIUM,
            List.of("Interior", "Exterior", "Audio", "Care"),
            List.of("Compatible model", "Colour", "Material"),
            List.of("Seat Cover Set", "Floor Mat", "Car Speaker", "Dashboard Polish"),
            List.of("Universal", "Swift", "i20", "Black", "Beige", "Leatherette", "Rubber")),
    TYRES("Tyres", Size.MEDIUM,
            List.of("Car Tyres", "Bike Tyres", "Tubes", "Alloy Wheels"),
            List.of("Size", "Compatible model", "Type"),
            List.of("Car Tyre", "Bike Tyre", "Tube", "Alloy Wheel"),
            List.of("165/80 R14", "185/65 R15", "90/90-18", "Tubeless", "Tube type", "Swift", "Splendor")),
    BATTERIES("Batteries", Size.MEDIUM,
            List.of("Car Batteries", "Bike Batteries", "Inverter Batteries", "Dry Cells"),
            List.of("Capacity", "Warranty", "Compatible model"),
            List.of("Car Battery", "Bike Battery", "Inverter Battery", "Dry Cell Pack"),
            List.of("35 Ah", "65 Ah", "150 Ah", "9 Ah", "24 months", "36 months", "Universal")),
    LUBRICANTS("Lubricants", Size.MEDIUM,
            List.of("Engine Oil", "Gear Oil", "Grease", "Coolant"),
            List.of("Volume", "Grade", "Compatible model"),
            List.of("Engine Oil", "Gear Oil", "Multipurpose Grease", "Radiator Coolant"),
            List.of("900 ml", "1 L", "3.5 L", "5 L", "20W-40", "10W-30", "Petrol", "Diesel")),
    TRACTOR_PARTS("Tractor parts", Size.MEDIUM,
            List.of("Tractor Spares", "Hydraulics", "Clutch", "Filters"),
            List.of("Manufacturer", "Compatible model", "Part number", "Specification"),
            List.of("Hydraulic Seal Kit", "Clutch Assembly", "Oil Filter", "Tractor Bearing"),
            List.of("Mahindra", "Swaraj", "Sonalika", "575", "744", "GP-TEST-PN-5", "OEM")),
    AGRI_EQUIPMENT("Agricultural equipment", Size.MEDIUM,
            List.of("Implements", "Sprayers", "Harvest", "Tillage"),
            List.of("Dimensions", "Material", "Capacity"),
            List.of("Cultivator Tyne", "Knapsack Sprayer", "Plough Share", "Rotavator Blade"),
            List.of("12 mm", "16 mm", "Cast iron", "Steel", "16 L", "20 L")),
    SEEDS("Seeds", Size.SMALL,
            List.of("Vegetable Seeds", "Cereal Seeds", "Flower Seeds", "Hybrid"),
            List.of("Weight", "Variety", "Germination"),
            List.of("Tomato Seeds", "Wheat Seeds", "Marigold Seeds", "Hybrid Maize Seeds"),
            List.of("50 g", "100 g", "1 kg", "5 kg", "Hybrid", "Desi", "85%", "90%")),
    FERTILIZER("Fertilizer", Size.MEDIUM,
            List.of("Nitrogen", "Phosphate", "Organic", "Micronutrients"),
            List.of("Weight", "Grade", "Form"),
            List.of("Urea Bag", "DAP Bag", "Vermicompost", "Zinc Sulphate"),
            List.of("25 kg", "45 kg", "50 kg", "46-0-0", "18-46-0", "Granular", "Powder")),
    IRRIGATION("Irrigation supplies", Size.MEDIUM,
            List.of("Drip", "Sprinkler", "Pipes", "Pumps"),
            List.of("Size", "Material", "Capacity"),
            List.of("Drip Lateral Pipe", "Sprinkler Nozzle", "HDPE Pipe", "Water Pump"),
            List.of("12 mm", "16 mm", "63 mm", "HDPE", "Brass", "1 HP", "2 HP")),
    ANIMAL_FEED("Animal feed", Size.MEDIUM,
            List.of("Cattle Feed", "Poultry Feed", "Supplements", "Fodder"),
            List.of("Weight", "Protein", "Animal"),
            List.of("Cattle Feed Bag", "Poultry Starter", "Mineral Mixture", "Fodder Seed"),
            List.of("25 kg", "50 kg", "18%", "22%", "Cattle", "Poultry", "Goat")),
    PET("Pet supplies", Size.SMALL,
            List.of("Dog Food", "Cat Food", "Grooming", "Accessories"),
            List.of("Weight", "Life stage", "Animal"),
            List.of("Adult Dog Food", "Puppy Food", "Cat Litter", "Pet Shampoo", "Dog Collar"),
            List.of("1 kg", "3 kg", "10 kg", "Adult", "Puppy", "Kitten", "Dog", "Cat")),
    GARDENING("Gardening", Size.SMALL,
            List.of("Pots", "Soil", "Tools", "Plants"),
            List.of("Size", "Material", "Capacity"),
            List.of("Ceramic Pot", "Potting Soil", "Garden Trowel", "Indoor Plant"),
            List.of("6 inch", "8 inch", "12 inch", "Ceramic", "Plastic", "5 kg", "10 kg")),
    FLOWERS("Flowers", Size.MICRO,
            List.of("Bouquets", "Loose Flowers", "Garlands", "Plants"),
            List.of("Occasion", "Colour", "Size"),
            List.of("Rose Bouquet", "Marigold Loose", "Jasmine Garland", "Orchid Bunch"),
            List.of("Birthday", "Wedding", "Pooja", "Red", "Yellow", "White", "Small", "Large")),
    WATCHES("Watches", Size.SMALL,
            List.of("Analog", "Digital", "Smart Watches", "Straps"),
            List.of("Brand", "Dial size", "Colour", "Strap material"),
            List.of("Analog Watch", "Digital Watch", "Smart Watch", "Leather Strap"),
            List.of("Titan", "Casio", "Fastrack", "38 mm", "42 mm", "Black", "Silver", "Leather", "Metal")),
    LIGHTING("Home lighting", Size.MEDIUM,
            List.of("Ceiling Lights", "Lamps", "Decorative", "Outdoor"),
            List.of("Power", "Colour temperature", "Material"),
            List.of("LED Panel Light", "Table Lamp", "String Lights", "Gate Light"),
            List.of("9 W", "12 W", "18 W", "24 W", "Warm white", "Cool white", "Aluminium", "Plastic")),
    SECURITY("CCTV / security equipment", Size.MEDIUM,
            List.of("Cameras", "Recorders", "Alarms", "Accessories"),
            List.of("Resolution", "Storage", "Connectivity"),
            List.of("Dome Camera", "Bullet Camera", "DVR", "Door Alarm"),
            List.of("2 MP", "5 MP", "1 TB", "2 TB", "Wi-Fi", "Wired", "PoE")),
    SOLAR("Solar equipment", Size.MEDIUM,
            List.of("Panels", "Inverters", "Batteries", "Lights"),
            List.of("Capacity", "Warranty", "Type"),
            List.of("Solar Panel", "Solar Inverter", "Solar Battery", "Solar Street Light"),
            List.of("100 W", "330 W", "1 kW", "3 kW", "150 Ah", "25 years", "5 years", "Mono", "Poly")),
    INVERTER("Inverter / UPS", Size.MEDIUM,
            List.of("Inverters", "UPS", "Batteries", "Stabilisers"),
            List.of("Capacity", "Warranty", "Type"),
            List.of("Home Inverter", "Online UPS", "Tubular Battery", "Voltage Stabiliser"),
            List.of("600 VA", "900 VA", "1100 VA", "150 Ah", "24 months", "Sine wave", "Square wave")),
    WATER_PURIFIER("Water purifier", Size.SMALL,
            List.of("RO Purifiers", "UV Purifiers", "Filters", "Spares"),
            List.of("Capacity", "Technology", "Warranty"),
            List.of("RO Water Purifier", "UV Purifier", "RO Membrane", "Sediment Filter"),
            List.of("6 L", "8 L", "10 L", "RO+UV", "UV", "12 months", "24 months")),
    DISPOSABLES("Disposable products", Size.MEDIUM,
            List.of("Plates & Cups", "Cutlery", "Containers", "Tissue"),
            List.of("Pack size", "Material", "Dimensions"),
            List.of("Paper Plate", "Plastic Cup", "Food Container", "Tissue Roll"),
            List.of("Pack of 50", "Pack of 100", "Paper", "Plastic", "6 inch", "500 ml")),
    PACKAGING("Packaging materials", Size.LARGE,
            List.of("Cartons", "Tapes", "Bags", "Protective"),
            List.of("Dimensions", "Material", "Pack size", "GSM"),
            List.of("Corrugated Box", "Packing Tape", "Poly Bag", "Bubble Wrap"),
            List.of("12x10x8 inch", "18x12x10 inch", "2 inch", "3 inch", "Kraft", "LDPE", "Pack of 100", "120 GSM")),
    CLEANING("Cleaning supplies", Size.MEDIUM,
            List.of("Floor Care", "Bathroom", "Kitchen", "Tools"),
            List.of("Volume", "Fragrance", "Pack size"),
            List.of("Floor Cleaner", "Toilet Cleaner", "Dish Wash Liquid", "Microfibre Cloth"),
            List.of("500 ml", "1 L", "5 L", "Lemon", "Pine", "Pack of 3")),
    POOJA("Religious / pooja products", Size.SMALL,
            List.of("Idols", "Incense", "Lamps", "Pooja Kits"),
            List.of("Material", "Size", "Occasion"),
            List.of("Brass Idol", "Agarbatti Pack", "Brass Diya", "Pooja Thali Set"),
            List.of("Brass", "Marble", "Clay", "3 inch", "6 inch", "12 inch", "Diwali", "Daily"));

    /**
     * How many lines this kind of shop carries.
     *
     * <p>Deliberately uneven. Code that quietly assumes every shop is the same
     * size - a page that fetches "all products", a screen that never paginates -
     * behaves perfectly until it meets the kirana, and these bands are what
     * make the kirana exist.
     */
    enum Size {
        MICRO(5, 20),
        SMALL(20, 75),
        MEDIUM(75, 250),
        LARGE(250, 400),
        HUGE(480, 520);

        final int min;
        final int max;

        Size(int min, int max) {
            this.min = min;
            this.max = max;
        }
    }

    final String label;
    final Size size;
    /** What this trade calls its departments. No two lists are the same. */
    final List<String> categories;
    /** The attribute NAMES this trade tells two sellable things apart by. */
    final List<String> attributeNames;
    /** Recognisable product stems - never "Product 1". */
    final List<String> productStems;
    /** Values the attributes above draw from. */
    final List<String> attributeValues;

    Trade(String label, Size size, List<String> categories, List<String> attributeNames,
          List<String> productStems, List<String> attributeValues) {
        this.label = label;
        this.size = size;
        this.categories = categories;
        this.attributeNames = attributeNames;
        this.productStems = productStems;
        this.attributeValues = attributeValues;
    }
}
