-- Re-syncs every identity/serial sequence with the largest id actually in its
-- table.
--
-- THE BUG THIS FIXES: admin "Add Product" answered
--
--     409 "That conflicts with something that already exists."
--
-- for every product, including brand new names that collide with nothing.
-- There is no unique constraint on products.name. The conflict was on
-- products_pkey - the application was generating an id that a row already
-- had.
--
-- Reproduced exactly:
--
--     INSERT INTO products (id, name, ...) VALUES (4179, ...);  -- explicit id
--     INSERT INTO products (name, ...)     VALUES (...);        -- app insert
--     ERROR: duplicate key value violates unique constraint "products_pkey"
--     DETAIL: Key (id)=(4179) already exists.
--
-- Hibernate maps @GeneratedValue(strategy = IDENTITY) onto
-- GENERATED BY DEFAULT AS IDENTITY, not GENERATED ALWAYS. "BY DEFAULT" means
-- an INSERT is allowed to supply its own id - and when it does, the sequence
-- behind the column is NOT advanced. So one row inserted by hand in a SQL
-- console, one restored dump, one CSV import, and the sequence is permanently
-- behind the table. Every application insert from then on asks for an id that
-- is already taken, and keeps failing until the sequence has crawled back past
-- the highest manual id one collision at a time.
--
-- That is a server-side defect that was being reported to the admin as if
-- their input were at fault, which is why it survived so long.
--
-- FORWARD ONLY. setval never moves a sequence backwards here. Moving one back
-- would hand out ids that are already in use - the same failure this migration
-- exists to end, inflicted deliberately.
--
-- OWNED SEQUENCES ONLY. pg_get_serial_sequence returns only the sequence a
-- column owns (identity or serial). Standalone sequences - order_items_seq
-- (V10) and order_number_seq (V6) - are handed out by Hibernate in blocks and
-- are SUPPOSED to run ahead of the table, so resetting them to max(id) would
-- reissue ids that Hibernate has already allocated in memory. They are not
-- owned by any column, so they are not matched here, and that is deliberate
-- rather than an oversight.
--
-- Safe on an empty database. On a first boot Flyway runs before Hibernate has
-- created any table, information_schema is empty, and the loop below does
-- nothing.

DO $$
DECLARE
    col        RECORD;
    seq_name   TEXT;
    max_id     BIGINT;
    seq_value  BIGINT;
    moved      INT := 0;
BEGIN
    FOR col IN
        SELECT table_schema, table_name, column_name
        FROM information_schema.columns
        WHERE table_schema = current_schema()
    LOOP
        seq_name := pg_get_serial_sequence(
                        quote_ident(col.table_schema) || '.' || quote_ident(col.table_name),
                        col.column_name);

        CONTINUE WHEN seq_name IS NULL;

        EXECUTE format('SELECT COALESCE(max(%I), 0) FROM %I.%I',
                       col.column_name, col.table_schema, col.table_name)
        INTO max_id;

        -- NULL when the sequence has never been read from, which is the
        -- "fresh table" case - COALESCE to 0 so a populated table with an
        -- untouched sequence still gets corrected.
        seq_value := COALESCE(pg_sequence_last_value(seq_name::regclass), 0);

        IF max_id > seq_value THEN
            PERFORM setval(seq_name, max_id, true);
            moved := moved + 1;
            RAISE NOTICE 'Re-synced % from % to % (table %.% held a higher id than its sequence)',
                         seq_name, seq_value, max_id, col.table_schema, col.table_name;
        END IF;
    END LOOP;

    RAISE NOTICE 'Identity sequence re-sync complete: % sequence(s) moved forward.', moved;
END $$;
