-- A refund becomes a row, so a shop can send money back more than once.
--
-- WHAT WAS WRONG. Refunds lived in six columns on payments: one refund id,
-- one amount, one timestamp. That shape can hold exactly one refund per
-- payment, so the second one had nowhere to go. V37 said as much in its own
-- comment - "the day partials arrive, the history is already correct" - and
-- partials did arrive, but only one per payment, because refunding again
-- would have overwritten the first refund's record with the second's.
--
-- A customer who returns two items on separate days is not an edge case in a
-- kirana shop; it is Tuesday. Overwriting the first refund would have left
-- the shop's own books claiming it sent back 200 when it had sent 350, and
-- the difference is invisible until someone reconciles against the bank.
--
-- WHY THE PAYMENTS COLUMNS STAY. They are now a SUMMARY of these rows, not
-- the record: refund_amount is the sum that has gone back, refunded_at is
-- when the last one landed. Everything that already reads them - the admin
-- screen, the money-health alert, the reconciliation index - keeps working
-- and keeps meaning the same thing. Dropping them would have made this
-- migration a rewrite of five other features instead of an addition.
--
-- IDEMPOTENCY IS PRESERVED ACROSS THE MIGRATION, which is the one thing that
-- could have cost real money here. Cashfree dedups on our refund id, and
-- every refund ever sent used "gpsr-<paymentId>". The backfill below writes
-- that exact id onto the row it creates, and the application keeps issuing
-- it for a payment's FIRST refund - so a retry of a refund that was in
-- flight when this deploys still carries the id Cashfree has already seen.
-- Only the second and later refunds on a payment take the suffixed form.

-- ---------------------------------------------------------------------------
-- PARTIALLY_REFUNDED has to be allowed before anything can write it.
--
-- payment_status carries a CHECK constraint listing every status by name -
-- generated by Hibernate when the schema was first built, and therefore
-- frozen at whatever the enum held that day. Production runs ddl-auto=validate,
-- which checks columns and types and does NOT look at check constraints, so
-- adding the enum value in Java alone would deploy cleanly and then fail at
-- the first partial refund, at the worst possible moment: mid-refund, with a
-- customer waiting for money.
--
-- Dropped by name and recreated rather than altered, because Postgres has no
-- ALTER ... CHECK. IF EXISTS so this runs on a database built by a different
-- route, where the constraint may never have existed.
-- ---------------------------------------------------------------------------
ALTER TABLE payments DROP CONSTRAINT IF EXISTS payments_payment_status_check;

ALTER TABLE payments ADD CONSTRAINT payments_payment_status_check
    CHECK (payment_status IN (
        'PENDING', 'SUCCESS', 'FAILED',
        'COD_PENDING', 'COD_RECEIVED',
        'REFUND_PENDING', 'REFUNDED', 'PARTIALLY_REFUNDED',
        'CANCELLED', 'EXPIRED'
    ));

CREATE TABLE IF NOT EXISTS refunds (
    id                    BIGSERIAL PRIMARY KEY,
    payment_id            BIGINT NOT NULL REFERENCES payments (id),

    -- Which refund this is against that payment: 1, 2, 3. Drives the refund
    -- id, so it must be stable once written.
    sequence_no           INTEGER NOT NULL CHECK (sequence_no >= 1),

    -- NEVER zero or negative. A refund for nothing is not a refund, and a
    -- negative one is a charge wearing a refund's name.
    amount                NUMERIC(12, 2) NOT NULL CHECK (amount > 0),

    -- PENDING, SUCCEEDED, FAILED. Text rather than an enum type so adding a
    -- state later is a code change, not a migration with an exclusive lock.
    status                VARCHAR(16) NOT NULL,

    -- CASH or GATEWAY, same meaning as on payments: a COD refund never went
    -- near a provider and must not be reconciled against one.
    channel               VARCHAR(16) NOT NULL,

    -- Our id, and Cashfree's idempotency key. Unique across the table, which
    -- is what makes a double-send impossible to record twice.
    refund_id             VARCHAR(64) NOT NULL,
    provider_refund_id    VARCHAR(64),

    -- Free text from the shopkeeper: "two atta returned". Not shown to the
    -- customer, and deliberately not a fixed list - a shop's reasons are its
    -- own and an enum would just get an OTHER value that means nothing.
    reason                VARCHAR(255),
    failure_reason        VARCHAR(255),

    -- The moment the provider took the request. The clock the stuck-refund
    -- alert measures against, so it is set once and never touched again.
    requested_at          TIMESTAMP,
    settled_at            TIMESTAMP,
    created_at            TIMESTAMP NOT NULL DEFAULT NOW()
);

-- One row per refund id. This is the constraint that makes an at-least-once
-- outbox safe: a redelivered send cannot insert a second row for the same
-- refund, it collides here.
CREATE UNIQUE INDEX IF NOT EXISTS ux_refunds_refund_id ON refunds (refund_id);

-- And one row per (payment, sequence), so two concurrent refunds on the same
-- payment cannot both claim to be number 2. The transaction takes the
-- payment row lock first, but a unique index is the thing that is still true
-- if somebody later writes a path that forgets to.
CREATE UNIQUE INDEX IF NOT EXISTS ux_refunds_payment_sequence
    ON refunds (payment_id, sequence_no);

-- The only per-payment query: every refund on this payment, newest first.
CREATE INDEX IF NOT EXISTS ix_refunds_payment ON refunds (payment_id, id DESC);

-- The reconciliation's query: gateway refunds asked for and not yet landed,
-- oldest first. Partial, so it indexes the handful actually in flight rather
-- than every refund the shop has ever made.
CREATE INDEX IF NOT EXISTS ix_refunds_awaiting_provider
    ON refunds (requested_at)
    WHERE status = 'PENDING' AND channel = 'GATEWAY';

-- ---------------------------------------------------------------------------
-- Backfill: every refund that already happened becomes a row.
--
-- WITHOUT THIS the remaining-to-refund sum reads zero for every historical
-- refund, and a shop could send back the full amount a second time on an
-- order it has already refunded. That is the migration's most expensive
-- possible bug, so it runs in the same transaction as the table creation.
--
-- The WHERE clause is what makes a refund "real": an amount was recorded, or
-- a refund id was issued, or the payment reached a refund status. A payment
-- merely marked REFUND_PENDING by a cancellation - an intention with no id,
-- no channel and no amount - is deliberately NOT backfilled, because no
-- money has been promised back yet and inventing a row would make the
-- reconciliation chase a refund nobody ever sent.
-- ---------------------------------------------------------------------------
INSERT INTO refunds (
    payment_id, sequence_no, amount, status, channel,
    refund_id, provider_refund_id, reason, failure_reason,
    requested_at, settled_at, created_at
)
SELECT
    p.id,
    1,
    -- An amount is required and must be positive. A REFUNDED payment with no
    -- recorded refund_amount predates V37; the whole payment came back, which
    -- is what "refunded" meant before partials existed.
    COALESCE(NULLIF(p.refund_amount, 0), p.amount),
    CASE
        WHEN p.payment_status = 'REFUNDED' THEN 'SUCCEEDED'
        WHEN p.refund_failure_reason IS NOT NULL THEN 'FAILED'
        ELSE 'PENDING'
    END,
    -- refund_channel is null on refunds a cancellation started before V37.
    -- isCashRefund's rule, in SQL: money that never went through a provider
    -- is cash. Getting this wrong in the safe direction matters - calling a
    -- gateway refund CASH would hide it from reconciliation, so the test is
    -- on the provider id, which cannot be null for a real gateway payment.
    COALESCE(
        p.refund_channel,
        CASE
            WHEN p.payment_method = 'COD' THEN 'CASH'
            WHEN p.provider_order_id IS NULL OR p.provider_order_id = '' THEN 'CASH'
            ELSE 'GATEWAY'
        END
    ),
    -- The id already at the provider. Must match refundIdFor() exactly.
    COALESCE(p.refund_id, 'gpsr-' || p.id),
    p.provider_refund_id,
    NULL,
    p.refund_failure_reason,
    p.refund_requested_at,
    p.refunded_at,
    COALESCE(p.refund_requested_at, p.refunded_at, NOW())
FROM payments p
WHERE (p.refund_amount IS NOT NULL
       OR p.refund_id IS NOT NULL
       OR p.payment_status = 'REFUNDED')
  AND COALESCE(NULLIF(p.refund_amount, 0), p.amount) > 0
  -- Idempotent: this migration can be re-applied to a database that already
  -- carries the rows without duplicating them.
  AND NOT EXISTS (SELECT 1 FROM refunds r WHERE r.payment_id = p.id);
