-- Slice 0 of the multi-merchant transformation: introduce tenancy WITHOUT
-- changing behaviour.
--
-- After this migration the schema can describe many shops. Nothing reads
-- shop_id yet - no query filters on it, no endpoint accepts it, no screen
-- shows it - so the running application behaves exactly as it did before.
-- That is the point: the risky part of a tenancy change is the backfill, and
-- doing it while nothing depends on the result means a mistake is visible
-- before it can serve one shop's data to another.
--
-- See docs/architecture/02-parity-architecture-migration.md for the slice
-- sequence this belongs to.
--
-- IF NOT EXISTS THROUGHOUT, and it is not defensive habit. FlywayAfterSchemaConfig
-- runs Flyway AFTER Hibernate when ddl-auto=update (a local bootstrap), so by
-- the time this script runs Hibernate has already created merchants and shops
-- from the @Entity classes. Under ddl-auto=validate (production) Flyway runs
-- first and this script IS the schema. Both orderings have to work.

-- ---------------------------------------------------------------- merchants

CREATE TABLE IF NOT EXISTS merchants (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legal_name      VARCHAR(200) NOT NULL,
    display_name    VARCHAR(200),
    contact_name    VARCHAR(160),
    contact_email   VARCHAR(190),
    contact_phone   VARCHAR(20),
    status          VARCHAR(30)  NOT NULL,
    status_reason   VARCHAR(500),
    is_demo         BOOLEAN      NOT NULL DEFAULT FALSE,
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6),
    deleted_at      TIMESTAMP(6)
);

-- -------------------------------------------------------------------- shops

CREATE TABLE IF NOT EXISTS shops (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id             BIGINT       NOT NULL,
    code                    VARCHAR(40)  NOT NULL,
    display_name            VARCHAR(200) NOT NULL,
    status                  VARCHAR(30)  NOT NULL,
    status_reason           VARCHAR(500),
    latitude                DOUBLE PRECISION,
    longitude               DOUBLE PRECISION,
    max_delivery_radius_km  NUMERIC(6,2),
    time_zone               VARCHAR(60),
    address_line            VARCHAR(300),
    locality                VARCHAR(120),
    city                    VARCHAR(120),
    state                   VARCHAR(120),
    pincode                 VARCHAR(12),
    support_phone           VARCHAR(30),
    support_email           VARCHAR(190),
    support_whatsapp        VARCHAR(30),
    is_demo                 BOOLEAN      NOT NULL DEFAULT FALSE,
    active                  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMP(6),
    updated_at              TIMESTAMP(6),
    deleted_at              TIMESTAMP(6)
);

-- A shop code is how a person names a shop in a URL, a report or a support
-- call. Reusing one would silently re-point every one of those.
CREATE UNIQUE INDEX IF NOT EXISTS ux_shops_code ON shops (code);

CREATE INDEX IF NOT EXISTS idx_shops_merchant_id ON shops (merchant_id);
CREATE INDEX IF NOT EXISTS idx_merchants_status  ON merchants (status);
CREATE INDEX IF NOT EXISTS idx_shops_status      ON shops (status);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'fk_shops_merchant' AND table_name = 'shops'
    ) THEN
        ALTER TABLE shops
            ADD CONSTRAINT fk_shops_merchant
            FOREIGN KEY (merchant_id) REFERENCES merchants (id);
    END IF;
END $$;

-- ------------------------------------------------------------ 1. add column
--
-- Nullable, every one of them. A NOT NULL column added to a populated table
-- has to be filled in the same statement, which turns "add a column" into
-- "rewrite every row of orders" inside one lock. Adding it empty is
-- instantaneous and safe to deploy on its own; the NOT NULL comes in a later
-- slice, after every writer sets it.
--
-- WHICH TABLES. Only the ones a SHOP owns. Deliberately absent:
--
--   products, product_variants, categories   the CENTRAL CATALOGUE. A shop
--       sells a product; it does not own the fact that the product exists.
--       Tagging them with a shop now would build exactly the model the brief
--       asks us to avoid, and would have to be undone in the catalogue split.
--
--   cart_items, order_items, order_return_items, refunds, payment_provider_events
--       child rows. Their tenant is their parent's, and a second copy of a
--       fact is a second chance for the two to disagree.
--
--   customers, addresses, wishlist    the CUSTOMER is platform-level (§4).
--       One account, orders from any shop.
--
--   outbox_events, shedlock, idempotency_records, otp_verifications,
--   refresh_tokens, search_synonyms, r2_staging_objects, ops_backup_runs,
--   client_crash_reports, customer_app_sessions   platform infrastructure.

ALTER TABLE orders                    ADD COLUMN IF NOT EXISTS shop_id BIGINT;
ALTER TABLE payments                  ADD COLUMN IF NOT EXISTS shop_id BIGINT;
ALTER TABLE deliveries                ADD COLUMN IF NOT EXISTS shop_id BIGINT;
ALTER TABLE delivery_batches          ADD COLUMN IF NOT EXISTS shop_id BIGINT;
ALTER TABLE delivery_partners         ADD COLUMN IF NOT EXISTS shop_id BIGINT;
ALTER TABLE invoices                  ADD COLUMN IF NOT EXISTS shop_id BIGINT;
ALTER TABLE order_returns             ADD COLUMN IF NOT EXISTS shop_id BIGINT;
ALTER TABLE coupons                   ADD COLUMN IF NOT EXISTS shop_id BIGINT;
ALTER TABLE inventory                 ADD COLUMN IF NOT EXISTS shop_id BIGINT;
ALTER TABLE store_operations_settings ADD COLUMN IF NOT EXISTS shop_id BIGINT;
ALTER TABLE delivery_pricing_settings ADD COLUMN IF NOT EXISTS shop_id BIGINT;
ALTER TABLE catalog_import_runs       ADD COLUMN IF NOT EXISTS shop_id BIGINT;
ALTER TABLE order_scan_events         ADD COLUMN IF NOT EXISTS shop_id BIGINT;
ALTER TABLE customer_delivery_ratings ADD COLUMN IF NOT EXISTS shop_id BIGINT;

-- ------------------------------------------------ 2. create Shop #1, 3. backfill
--
-- Everything that exists today belongs to the shop that has been trading all
-- along (§104: we are not replacing it, we are making it the first shop on
-- the platform).
--
-- IDEMPOTENT. Re-running finds the shop already there and the rows already
-- pointed at it, and does nothing. Flyway will not re-run an applied version,
-- but a backfill that cannot survive being run twice is one that cannot be
-- resumed after an interrupted deploy either.
--
-- The row is created here rather than left to ShopBootstrap because a
-- backfill needs a target NOW, in this transaction. ShopBootstrap covers the
-- other direction - a database created by Hibernate rather than by Flyway -
-- and skips its work when this has already run.

DO $$
DECLARE
    v_merchant_id BIGINT;
    v_shop_id     BIGINT;
    t             TEXT;
BEGIN
    SELECT id INTO v_shop_id FROM shops WHERE code = 'SHOP-1';

    IF v_shop_id IS NULL THEN
        SELECT id INTO v_merchant_id FROM merchants ORDER BY id LIMIT 1;

        IF v_merchant_id IS NULL THEN
            INSERT INTO merchants (legal_name, display_name, status, status_reason,
                                   is_demo, active, created_at, updated_at)
            VALUES ('UNNAMED MERCHANT - set platform.first-merchant.legal-name',
                    'GP Store',
                    'ACTIVE',
                    'The original GP-STORE shop, trading before the marketplace existed.',
                    FALSE, TRUE, now(), now())
            RETURNING id INTO v_merchant_id;
        END IF;

        -- Geography and contact details are left NULL here and filled by
        -- ShopBootstrap from the STORE_* configuration the application is
        -- actually running on. SQL cannot read the environment, and copying
        -- the defaults into the migration would freeze today's coordinates
        -- into a file nobody looks at again.
        INSERT INTO shops (merchant_id, code, display_name, status,
                           is_demo, active, created_at, updated_at)
        VALUES (v_merchant_id, 'SHOP-1', 'GP Store', 'ACTIVE',
                FALSE, TRUE, now(), now())
        RETURNING id INTO v_shop_id;
    END IF;

    UPDATE orders                    SET shop_id = v_shop_id WHERE shop_id IS NULL;
    UPDATE payments                  SET shop_id = v_shop_id WHERE shop_id IS NULL;
    UPDATE deliveries                SET shop_id = v_shop_id WHERE shop_id IS NULL;
    UPDATE delivery_batches          SET shop_id = v_shop_id WHERE shop_id IS NULL;
    UPDATE delivery_partners         SET shop_id = v_shop_id WHERE shop_id IS NULL;
    UPDATE invoices                  SET shop_id = v_shop_id WHERE shop_id IS NULL;
    UPDATE order_returns             SET shop_id = v_shop_id WHERE shop_id IS NULL;
    UPDATE coupons                   SET shop_id = v_shop_id WHERE shop_id IS NULL;
    UPDATE inventory                 SET shop_id = v_shop_id WHERE shop_id IS NULL;
    UPDATE store_operations_settings SET shop_id = v_shop_id WHERE shop_id IS NULL;
    UPDATE delivery_pricing_settings SET shop_id = v_shop_id WHERE shop_id IS NULL;
    UPDATE catalog_import_runs       SET shop_id = v_shop_id WHERE shop_id IS NULL;
    UPDATE order_scan_events         SET shop_id = v_shop_id WHERE shop_id IS NULL;
    UPDATE customer_delivery_ratings SET shop_id = v_shop_id WHERE shop_id IS NULL;

    -- A BACKFILL ALONE IS NOT ENOUGH, and this is the part that is easy to
    -- miss. Nothing in the application writes shop_id yet - that is Slice 1 -
    -- so the moment the first INSERT lands after this migration, the very
    -- invariant just established is broken again. Backfilling without this
    -- default leaves a table that was correct for exactly as long as nobody
    -- used it. Caught by the full test suite, which inserted 256 unassigned
    -- inventory rows within one run.
    --
    -- Under SINGLE_SHOP the default is simply true: there is one shop, and
    -- every new row belongs to it. Slice 1 removes these defaults as it
    -- teaches each writer to set the value explicitly from the tenant
    -- context - a default that outlives its slice would silently file a
    -- second shop's rows under the first.
    --
    -- Written with the resolved id rather than a literal 1: on a database
    -- where the identity sequence has moved, Shop #1 is not necessarily id 1.
    FOREACH t IN ARRAY ARRAY[
        'orders','payments','deliveries','delivery_batches','delivery_partners',
        'invoices','order_returns','coupons','inventory',
        'store_operations_settings','delivery_pricing_settings',
        'catalog_import_runs','order_scan_events','customer_delivery_ratings'
    ]
    LOOP
        EXECUTE format('ALTER TABLE %I ALTER COLUMN shop_id SET DEFAULT %s', t, v_shop_id);
    END LOOP;
END $$;

-- ----------------------------------------------------------- 4. VERIFY
--
-- §92: never assume a successful migration command means the data is correct.
--
-- This is the step that makes that instruction real rather than advice. If a
-- single row anywhere failed to be assigned a shop, the migration RAISES and
-- Flyway rolls the whole thing back - the deploy stops, loudly, with the
-- table named. The alternative is a deploy that reports success while leaving
-- orphan rows that will one day be invisible to every shop-scoped query.

DO $$
DECLARE
    t           TEXT;
    unassigned  BIGINT;
    problems    TEXT := '';
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'orders','payments','deliveries','delivery_batches','delivery_partners',
        'invoices','order_returns','coupons','inventory',
        'store_operations_settings','delivery_pricing_settings',
        'catalog_import_runs','order_scan_events','customer_delivery_ratings'
    ]
    LOOP
        EXECUTE format('SELECT count(*) FROM %I WHERE shop_id IS NULL', t) INTO unassigned;
        IF unassigned > 0 THEN
            problems := problems || format('%s has %s rows with no shop; ', t, unassigned);
        END IF;
    END LOOP;

    IF problems <> '' THEN
        RAISE EXCEPTION 'V46 backfill incomplete: %', problems;
    END IF;

    -- A shop pointing at a merchant that is not there would pass every column
    -- check and still be a broken row.
    IF EXISTS (SELECT 1 FROM shops s LEFT JOIN merchants m ON m.id = s.merchant_id
               WHERE m.id IS NULL) THEN
        RAISE EXCEPTION 'V46: a shop references a merchant that does not exist';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM shops WHERE code = 'SHOP-1') THEN
        RAISE EXCEPTION 'V46: Shop #1 was not created';
    END IF;
END $$;

-- Indexes on the new column. Added now rather than with the NOT NULL, because
-- the first query that filters by shop will want them and adding an index to
-- a large table later is the slower operation of the two.
CREATE INDEX IF NOT EXISTS idx_orders_shop_id            ON orders (shop_id);
CREATE INDEX IF NOT EXISTS idx_payments_shop_id          ON payments (shop_id);
CREATE INDEX IF NOT EXISTS idx_deliveries_shop_id        ON deliveries (shop_id);
CREATE INDEX IF NOT EXISTS idx_delivery_batches_shop_id  ON delivery_batches (shop_id);
CREATE INDEX IF NOT EXISTS idx_delivery_partners_shop_id ON delivery_partners (shop_id);
CREATE INDEX IF NOT EXISTS idx_invoices_shop_id          ON invoices (shop_id);
CREATE INDEX IF NOT EXISTS idx_order_returns_shop_id     ON order_returns (shop_id);
CREATE INDEX IF NOT EXISTS idx_coupons_shop_id           ON coupons (shop_id);
CREATE INDEX IF NOT EXISTS idx_inventory_shop_id         ON inventory (shop_id);
CREATE INDEX IF NOT EXISTS idx_import_runs_shop_id       ON catalog_import_runs (shop_id);
CREATE INDEX IF NOT EXISTS idx_scan_events_shop_id       ON order_scan_events (shop_id);
CREATE INDEX IF NOT EXISTS idx_cust_ratings_shop_id      ON customer_delivery_ratings (shop_id);
