-- V48: a shop's price list becomes its own thing, separate from the catalogue.
--
-- THE SHAPE THIS ESTABLISHES (§10):
--
--     products / product_variants          ONE row per real-world item, shared
--                                          by every shop. Identity, name, pack
--                                          size, barcode, photo, GST class.
--         |
--     shop_product_variants                ONE row per (shop, variant). Whether
--                                          THIS shop sells it, at what price,
--                                          with what offer.
--         |
--     inventory                            ONE row per (shop, variant). How many
--                                          units this shop has right now.
--
-- The catalogue is NOT duplicated per shop. Two kiranas both selling Aashirvaad
-- atta 5 kg point at the same product_variants row; what differs is their price
-- and their stock, which is exactly what these two child tables hold. Adding
-- Shop N adds rows, never tables and never code.
--
-- WHY PRICE AND STOCK ARE NOT THE SAME ROW, given both are keyed (shop,
-- variant). They have opposite write patterns. A price is edited by a person,
-- rarely. Stock is decremented under a row lock on every checkout, by the
-- exactly-once machinery in InventoryService. Putting them in one row would put
-- a price edit in contention with live checkouts, and would make every stock
-- decrement rewrite the price columns beside it. They are keyed alike because
-- they describe the same relationship; they are stored apart because one is hot.
--
-- WHAT product_variants KEEPS. Its selling_price / cost_price / mrp / available
-- stay, and stop being what a customer is charged: they become the CATALOGUE
-- DEFAULT - the terms a shop starts from when it begins stocking an item. That
-- is a real role, not a leftover, and it is what makes onboarding Shop N a
-- single INSERT rather than a data-entry exercise.

CREATE TABLE IF NOT EXISTS shop_product_variants (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id             BIGINT         NOT NULL REFERENCES shops (id),
    product_variant_id  BIGINT         NOT NULL REFERENCES product_variants (id),

    -- What this shop charges. NOT NULL: a shop that lists an item without
    -- naming a price is a checkout that cannot compute a total.
    selling_price       NUMERIC(38, 2) NOT NULL,

    -- What this shop paid. Never leaves the server; it is what makes the
    -- profit-based free-delivery rule work per shop rather than per catalogue.
    cost_price          NUMERIC(38, 2),

    -- The printed price on this shop's shelf. Null means "use the catalogue's",
    -- which is the normal case - MRP is a property of the pack, not the shop.
    mrp                 NUMERIC(38, 2),

    -- Listed and orderable at this shop. Distinct from stock: a shop can stop
    -- listing an item it still has units of.
    available           BOOLEAN        NOT NULL DEFAULT TRUE,
    active              BOOLEAN        NOT NULL DEFAULT TRUE,

    -- This shop's own ordering on its shelf, overriding the catalogue's.
    display_order       INTEGER,

    created_at          TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at          TIMESTAMP,

    CONSTRAINT uk_shop_product_variant UNIQUE (shop_id, product_variant_id),
    CONSTRAINT shop_product_variant_price_positive CHECK (selling_price > 0)
);

CREATE INDEX IF NOT EXISTS idx_shop_product_variants_shop    ON shop_product_variants (shop_id);
CREATE INDEX IF NOT EXISTS idx_shop_product_variants_variant ON shop_product_variants (product_variant_id);

-- ------------------------------------------------------- backfill Shop #1
--
-- Everything on the shelf today is something Shop #1 sells, at the price it
-- sells it for. Nothing about what a customer sees may change.
--
-- Variants with no selling price are skipped rather than defaulted: the CHECK
-- above says a listing needs a price, and inventing one would put a number in
-- front of a customer that nobody chose. They stay in the catalogue and are
-- simply not listed until somebody prices them - which is the same thing the
-- existing code does with a null price today.
DO $$
DECLARE
    v_shop_id  BIGINT;
    v_priced   BIGINT;
    v_unpriced BIGINT;
BEGIN
    SELECT id INTO v_shop_id FROM shops WHERE code = 'SHOP-1';
    IF v_shop_id IS NULL THEN
        RAISE EXCEPTION 'V48 cannot backfill: Shop #1 is missing (V46 should have created it)';
    END IF;

    INSERT INTO shop_product_variants
        (shop_id, product_variant_id, selling_price, cost_price, mrp, available, active, display_order)
    SELECT v_shop_id,
           v.id,
           v.selling_price,
           v.cost_price,
           v.mrp,
           coalesce(v.available, TRUE),
           coalesce(v.active, TRUE),
           v.display_order
    FROM product_variants v
    WHERE v.selling_price IS NOT NULL
      AND v.selling_price > 0
      AND NOT EXISTS (
          SELECT 1 FROM shop_product_variants s
          WHERE s.shop_id = v_shop_id AND s.product_variant_id = v.id);

    SELECT count(*) INTO v_priced FROM shop_product_variants WHERE shop_id = v_shop_id;
    SELECT count(*) INTO v_unpriced FROM product_variants v
        WHERE (v.selling_price IS NULL OR v.selling_price <= 0);

    RAISE NOTICE 'V48: Shop #1 now lists % variants; % variants have no price and were left unlisted',
        v_priced, v_unpriced;
END $$;

-- ------------------------------------------------- inventory becomes per shop
--
-- inventory already carries shop_id (V46) and is already filtered per shop, but
-- the UNIQUE on product_variant_id alone still says "one stock row in the whole
-- database per item" - which is a second shop's stock row failing to insert.
-- The key that is actually true is (shop, variant).
DO $$
DECLARE
    v_constraint TEXT;
BEGIN
    SELECT con.conname INTO v_constraint
    FROM pg_constraint con
    JOIN pg_class rel ON rel.oid = con.conrelid
    JOIN lateral unnest(con.conkey) k(attnum) ON TRUE
    JOIN pg_attribute att ON att.attrelid = rel.oid AND att.attnum = k.attnum
    WHERE rel.relname = 'inventory'
      AND con.contype = 'u'
      AND att.attname = 'product_variant_id'
    GROUP BY con.conname
    HAVING count(*) = 1;

    IF v_constraint IS NOT NULL THEN
        EXECUTE format('ALTER TABLE inventory DROP CONSTRAINT %I', v_constraint);
        RAISE NOTICE 'V48: dropped single-column unique % on inventory.product_variant_id', v_constraint;
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uk_inventory_shop_variant
    ON inventory (shop_id, product_variant_id);

-- ------------------------------------------------------------------ VERIFY
--
-- §92: a migration that ran is not the same as data that is right.
DO $$
DECLARE
    v_shop_id   BIGINT;
    v_mismatch  BIGINT;
    v_orphans   BIGINT;
BEGIN
    SELECT id INTO v_shop_id FROM shops WHERE code = 'SHOP-1';

    -- Every priced variant must now be listed by Shop #1 at exactly the price
    -- it was on sale for a moment ago. A single differing paisa here is a
    -- customer being charged something nobody decided.
    SELECT count(*) INTO v_mismatch
    FROM product_variants v
    LEFT JOIN shop_product_variants s
           ON s.product_variant_id = v.id AND s.shop_id = v_shop_id
    WHERE v.selling_price IS NOT NULL AND v.selling_price > 0
      AND (s.id IS NULL OR s.selling_price <> v.selling_price);

    IF v_mismatch > 0 THEN
        RAISE EXCEPTION 'V48 backfill is wrong: % priced variants are missing from Shop #1 or '
                        'are listed at a different price', v_mismatch;
    END IF;

    SELECT count(*) INTO v_orphans FROM shop_product_variants WHERE shop_id IS NULL;
    IF v_orphans > 0 THEN
        RAISE EXCEPTION 'V48 produced % listings belonging to no shop', v_orphans;
    END IF;
END $$;
