-- V49: the two settings tables stop being one row and become one row PER SHOP.
--
-- WHAT WAS WRONG WITH THEM. store_operations_settings and
-- delivery_pricing_settings were written as singletons - a primary key pinned
-- to 1 by a CHECK constraint, and a service that reads findById(1). That was
-- exactly right for one shop and is unusable for two: "are you taking orders
-- right now" and "what do you charge for delivery" are the most obviously
-- per-shop settings in the application, and under the singleton every merchant
-- would share one answer.
--
-- IT ALSO COULD NOT BE FIXED BY TAGGING THE ENTITY. A Hibernate filter rewrites
-- queries, and findById does not run one - so these two tables were the pair
-- named as still-unprotected in the Slice 1 report. Splitting the row is the
-- fix; the filter then covers them like every other shop-owned table.
--
-- NO PER-SHOP CODE. One row per shop, one lookup by the shop in scope. Shop N
-- adds a row.

-- ---------------------------------------------------- 1. free the primary key
ALTER TABLE store_operations_settings DROP CONSTRAINT IF EXISTS store_operations_settings_singleton;
ALTER TABLE delivery_pricing_settings DROP CONSTRAINT IF EXISTS delivery_pricing_settings_singleton;

-- The id was assigned by the application (always 1). With a row per shop the
-- database has to hand them out. GENERATED BY DEFAULT, not ALWAYS, so the
-- existing row keeps id 1 and nothing that already references it moves.
DO $$
DECLARE
    t        TEXT;
    v_max    BIGINT;
    is_ident TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY['store_operations_settings', 'delivery_pricing_settings']
    LOOP
        SELECT is_identity INTO is_ident FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = t AND column_name = 'id';

        IF is_ident = 'NO' THEN
            EXECUTE format('ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', t);
        END IF;

        EXECUTE format('SELECT coalesce(max(id), 0) FROM %I', t) INTO v_max;
        EXECUTE format('ALTER TABLE %I ALTER COLUMN id RESTART WITH %s', t, v_max + 1);
    END LOOP;
END $$;

-- ------------------------------------------- 2. one row per shop, enforced
--
-- The rows that exist belong to Shop #1 (V46 backfilled them). NOT NULL and a
-- unique index are what stop a second shop's settings being written without a
-- shop, or two rows being written for the same one.
DO $$
DECLARE
    v_shop_id BIGINT;
BEGIN
    SELECT id INTO v_shop_id FROM shops WHERE code = 'SHOP-1';
    IF v_shop_id IS NULL THEN
        RAISE EXCEPTION 'V49 cannot proceed: Shop #1 is missing';
    END IF;

    UPDATE store_operations_settings SET shop_id = v_shop_id WHERE shop_id IS NULL;
    UPDATE delivery_pricing_settings SET shop_id = v_shop_id WHERE shop_id IS NULL;
END $$;

ALTER TABLE store_operations_settings ALTER COLUMN shop_id SET NOT NULL;
ALTER TABLE delivery_pricing_settings ALTER COLUMN shop_id SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_store_operations_settings_shop
    ON store_operations_settings (shop_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_delivery_pricing_settings_shop
    ON delivery_pricing_settings (shop_id);

-- ------------------------------------------------- 3. the default comes off
--
-- Same reasoning as V47: a shop_id default answers "which shop" without
-- anybody deciding. These two kept theirs while they were singletons; they are
-- not singletons any more, and the entity listener now stamps them.
ALTER TABLE store_operations_settings ALTER COLUMN shop_id DROP DEFAULT;
ALTER TABLE delivery_pricing_settings ALTER COLUMN shop_id DROP DEFAULT;

-- ------------------------------------------------------------------ VERIFY
DO $$
DECLARE
    t       TEXT;
    bad     BIGINT;
    ident   TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY['store_operations_settings', 'delivery_pricing_settings']
    LOOP
        EXECUTE format('SELECT count(*) FROM %I WHERE shop_id IS NULL', t) INTO bad;
        IF bad > 0 THEN
            RAISE EXCEPTION 'V49: % still has % settings rows with no shop', t, bad;
        END IF;

        EXECUTE format('SELECT count(*) FROM (SELECT shop_id FROM %I GROUP BY shop_id '
                       'HAVING count(*) > 1) d', t) INTO bad;
        IF bad > 0 THEN
            RAISE EXCEPTION 'V49: % has more than one settings row for the same shop', t;
        END IF;

        SELECT is_identity INTO ident FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = t AND column_name = 'id';
        IF ident <> 'YES' THEN
            RAISE EXCEPTION 'V49: %.id is still application-assigned, so a second shop cannot '
                            'get a settings row', t;
        END IF;

        IF EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = current_schema() AND table_name = t
                     AND column_name = 'shop_id' AND column_default IS NOT NULL) THEN
            RAISE EXCEPTION 'V49 failed to remove the shop_id default from %', t;
        END IF;
    END LOOP;
END $$;
