-- V50: a staff account belongs to shops, and PLATFORM_ADMIN becomes a real role.
--
-- THE QUESTION THIS ANSWERS. Slice 1 resolves "which shop is this request for"
-- from the credential and nothing else. Under one shop the answer is trivially
-- Shop #1. Under a marketplace it has to come from somewhere real, and the two
-- candidates are a claim inside the JWT or a row in the database.
--
-- IT IS A ROW, NOT A CLAIM, and that is the same decision this codebase already
-- made for permissions: JwtFilter derives authorities from the LIVE account row
-- on every request rather than reading them out of the token, so a demotion
-- takes effect immediately instead of whenever the token happens to expire. A
-- shop claim in a token has the identical failure: move a manager between
-- shops, or remove them, and their existing token keeps working against the old
-- shop until it expires. shop_staff is the authoritative answer, re-read every
-- request.
--
-- ONE ACCOUNT, MANY SHOPS. A merchant who runs three kiranas gets three rows and
-- may operate exactly those three. Nothing about that needs per-shop code.

CREATE TABLE IF NOT EXISTS shop_staff (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id      BIGINT    NOT NULL REFERENCES shops (id),
    customer_id  BIGINT    NOT NULL REFERENCES customers (id),

    -- The shop this account lands in when the request names none. Exactly one
    -- per account, enforced by the partial unique index below - "which shop am
    -- I in" must have one answer, not a race between rows.
    is_default   BOOLEAN   NOT NULL DEFAULT FALSE,

    active       BOOLEAN   NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP NOT NULL DEFAULT now(),
    updated_at   TIMESTAMP,

    CONSTRAINT uk_shop_staff UNIQUE (shop_id, customer_id)
);

CREATE INDEX IF NOT EXISTS idx_shop_staff_customer ON shop_staff (customer_id);
CREATE INDEX IF NOT EXISTS idx_shop_staff_shop     ON shop_staff (shop_id);

-- One default shop per account, and only among the memberships that are live.
CREATE UNIQUE INDEX IF NOT EXISTS uk_shop_staff_one_default
    ON shop_staff (customer_id) WHERE is_default AND active;

-- --------------------------------------------------------- merchant owner
--
-- Who answers for the business. Needed to decide whether an account may change
-- a merchant's own record, and to give a new shop's staff list a first member
-- without anybody typing one in.
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS owner_customer_id BIGINT REFERENCES customers (id);
CREATE INDEX IF NOT EXISTS idx_merchants_owner ON merchants (owner_customer_id);

-- ------------------------------------------------------ PLATFORM_ADMIN role
--
-- customers.role carries a CHECK constraint (V32) listing every value this
-- build knows. ddl-auto=validate does not inspect check constraints, so adding
-- the enum value in Java without this migration passes startup and then rejects
-- every insert of the new role at runtime. The enum and this are a matched pair.
DO $$
DECLARE
    con_name TEXT;
BEGIN
    SELECT con.conname INTO con_name
    FROM pg_constraint con
    JOIN pg_class rel ON rel.oid = con.conrelid
    WHERE rel.relname = 'customers'
      AND con.contype = 'c'
      AND pg_get_constraintdef(con.oid) ILIKE '%role%'
    LIMIT 1;

    IF con_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE customers DROP CONSTRAINT %I', con_name);
    END IF;
END $$;

ALTER TABLE customers
    ADD CONSTRAINT customers_role_check
    CHECK (role IN (
        'CUSTOMER',
        'ADMIN',
        'DELIVERY_BOY',
        'SUPER_ADMIN',
        'MANAGER',
        'INVENTORY_MANAGER',
        'ORDER_MANAGER',
        'DELIVERY_MANAGER',
        'SUPPORT',
        -- New. Runs the marketplace, not a shop - see RolePermissions.
        'PLATFORM_ADMIN'
    ));

-- ----------------------------------------------- backfill Shop #1's staff
--
-- Every staff account that exists today works at the shop that exists today.
-- Without this, the first multi-shop deployment would leave every one of them
-- belonging to no shop and therefore unable to resolve a scope at all - the
-- shop's own manager locked out by a migration.
--
-- Riders are deliberately NOT included: a delivery_partners row already carries
-- its own shop_id, and a worker session never touches the customers table.
DO $$
DECLARE
    v_shop_id BIGINT;
    v_added   BIGINT;
BEGIN
    SELECT id INTO v_shop_id FROM shops WHERE code = 'SHOP-1';
    IF v_shop_id IS NULL THEN
        RAISE EXCEPTION 'V50 cannot backfill staff: Shop #1 is missing';
    END IF;

    INSERT INTO shop_staff (shop_id, customer_id, is_default, active)
    SELECT v_shop_id, c.id, TRUE, TRUE
    FROM customers c
    WHERE c.role IN ('ADMIN', 'SUPER_ADMIN', 'MANAGER', 'INVENTORY_MANAGER',
                     'ORDER_MANAGER', 'DELIVERY_MANAGER', 'SUPPORT')
      AND NOT EXISTS (SELECT 1 FROM shop_staff s
                      WHERE s.shop_id = v_shop_id AND s.customer_id = c.id);

    GET DIAGNOSTICS v_added = ROW_COUNT;
    RAISE NOTICE 'V50: % existing staff accounts now belong to Shop #1', v_added;

    -- The first merchant's owner is the shop owner, if there is one on record.
    UPDATE merchants m
       SET owner_customer_id = (
           SELECT c.id FROM customers c
           WHERE c.role IN ('SUPER_ADMIN', 'ADMIN')
           ORDER BY CASE c.role WHEN 'SUPER_ADMIN' THEN 0 ELSE 1 END, c.id
           LIMIT 1)
     WHERE m.owner_customer_id IS NULL
       AND m.id = (SELECT merchant_id FROM shops WHERE id = v_shop_id);
END $$;

-- ------------------------------------------------------------------ VERIFY
DO $$
DECLARE
    orphan_staff BIGINT;
    stranded     BIGINT;
BEGIN
    SELECT count(*) INTO orphan_staff FROM shop_staff WHERE shop_id IS NULL OR customer_id IS NULL;
    IF orphan_staff > 0 THEN
        RAISE EXCEPTION 'V50 produced % shop_staff rows with no shop or no account', orphan_staff;
    END IF;

    -- Every staff account must belong somewhere, or it cannot resolve a scope
    -- and its owner is simply locked out.
    SELECT count(*) INTO stranded
    FROM customers c
    WHERE c.role IN ('ADMIN', 'SUPER_ADMIN', 'MANAGER', 'INVENTORY_MANAGER',
                     'ORDER_MANAGER', 'DELIVERY_MANAGER', 'SUPPORT')
      AND NOT EXISTS (SELECT 1 FROM shop_staff s WHERE s.customer_id = c.id AND s.active);

    IF stranded > 0 THEN
        RAISE EXCEPTION 'V50: % staff accounts belong to no shop - they would be locked out', stranded;
    END IF;
END $$;
