-- V51: one basket, many shops, one order each.
--
-- WHAT §16 ASKS FOR. A customer fills a basket from two kiranas. Each shop
-- packs, prices, delivers and is paid for its own half; each can be cancelled
-- or refunded without touching the other. What holds them together is a
-- GROUP - the thing the customer thinks of as "my order" - and what the shops
-- work is the individual orders under it.
--
-- THE GROUP HAS NO shop_id, DELIBERATELY. It spans shops; that is its entire
-- job. Like customers and addresses (§4) it is platform-level, and the thing
-- that keeps one customer out of another's group is the ownership check that
-- already guards every customer-owned row.
--
-- NOTHING CHANGES UNDER ONE SHOP. A single-shop basket produces a group with
-- exactly one order in it, which is the same order it produced before. The
-- group row is created either way rather than only when a basket spans shops:
-- two code paths for "one shop" and "several" is how the rare one rots.

CREATE TABLE IF NOT EXISTS order_groups (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_number   VARCHAR(40)    NOT NULL UNIQUE,
    customer_id    BIGINT         NOT NULL REFERENCES customers (id),
    address_id     BIGINT         REFERENCES addresses (id),

    -- What the customer agreed to pay in total, across every shop. The
    -- authoritative per-shop amounts stay on the orders; this is the sum as
    -- it stood at checkout, kept because a total recomputed later from
    -- orders that have since been cancelled or refunded is not what they
    -- agreed to.
    total_amount   NUMERIC(38, 2) NOT NULL DEFAULT 0,
    shop_count     INTEGER        NOT NULL DEFAULT 1,

    created_at     TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at     TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_order_groups_customer ON order_groups (customer_id);

-- Which group an order belongs to. Nullable: every order placed before this
-- migration belongs to no group, and inventing one for them would be
-- inventing a checkout that never happened.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS order_group_id BIGINT REFERENCES order_groups (id);
CREATE INDEX IF NOT EXISTS idx_orders_group ON orders (order_group_id);

-- ------------------------------------------------- which shelf a cart line came from
--
-- A CART LINE NOW REMEMBERS ITS SHOP, and this is the column that makes the
-- split possible: at checkout the basket is grouped by it, and each group
-- becomes one shop's order.
--
-- IT IS NOT A TENANT BOUNDARY, and cart_items is deliberately NOT filtered by
-- it. A cart that could only ever show one shop's lines is not a multi-shop
-- cart - the customer would add something from the second kirana and watch
-- the first one's items vanish. What protects a cart is the same thing that
-- always protected it: it belongs to a customer, and CartService checks that
-- ownership on every read and write. The shop id here is data about the line,
-- not permission to see it.
--
-- IT IS ALSO NEVER SENT BY A CLIENT. CartService stamps it from the shop the
-- request resolved to, which is why changing it in a request body cannot move
-- an item between shops.
ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS shop_id BIGINT REFERENCES shops (id);
CREATE INDEX IF NOT EXISTS idx_cart_items_shop ON cart_items (shop_id);

DO $$
DECLARE
    v_shop_id BIGINT;
BEGIN
    SELECT id INTO v_shop_id FROM shops WHERE code = 'SHOP-1';
    IF v_shop_id IS NULL THEN
        RAISE EXCEPTION 'V51 cannot backfill: Shop #1 is missing';
    END IF;

    -- Everything in a basket today came off the one shop's shelf.
    UPDATE cart_items SET shop_id = v_shop_id WHERE shop_id IS NULL;
END $$;

-- ------------------------------------------------------------------ VERIFY
DO $$
DECLARE
    unassigned BIGINT;
    orphaned   BIGINT;
BEGIN
    SELECT count(*) INTO unassigned FROM cart_items WHERE shop_id IS NULL;
    IF unassigned > 0 THEN
        RAISE EXCEPTION 'V51 left % cart lines with no shop - they could never be checked out',
            unassigned;
    END IF;

    -- A group with no orders under it, or an order pointing at a group that
    -- is not there, would each be a checkout somebody cannot see the whole of.
    SELECT count(*) INTO orphaned FROM orders o
    WHERE o.order_group_id IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM order_groups g WHERE g.id = o.order_group_id);
    IF orphaned > 0 THEN
        RAISE EXCEPTION 'V51: % orders point at a group that does not exist', orphaned;
    END IF;
END $$;
