-- ONE TERRITORY STAMP PER SHOP PER ADDRESS.
--
-- addresses.subzone_id and addresses.subzone_locked held ONE answer to a
-- question that has one answer per shop: "which of your territories is this
-- house in, and has a person placed it there by hand?" On a marketplace an
-- address genuinely sits in every map that covers it, so the single column
-- meant the shops overwrote each other:
--
--   * whichever shop last saved the address, re-resolved its map, or pinned
--     the row won, and every other shop's stamp was gone;
--   * subzone_locked is read by every shop's re-resolve, so one merchant
--     pinning an address froze it for all of them;
--   * a shop reading a stamp that belonged to another shop got no answer at
--     all (the row is shop-owned, so the tenant filter hides it), and fell
--     back to resolving live - which is precisely the drift the stamp exists
--     to prevent.
--
-- This table gives the answer the shape the question has. It is shop-owned,
-- so the ordinary tenant filter narrows every read to the shop asking, and no
-- shop can see, overwrite or lock another shop's stamp.
CREATE TABLE IF NOT EXISTS address_territory_stamps (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id     BIGINT    NOT NULL REFERENCES shops (id),
    address_id  BIGINT    NOT NULL REFERENCES addresses (id) ON DELETE CASCADE,
    -- NULL IS A REAL ANSWER, and it is not the same as having no row. A stamp
    -- with no subzone says "this shop looked, and this house is outside every
    -- territory it has drawn" - which shows up as a FALLBACK assignment an
    -- administrator can go and fix. No row at all says "this shop has never
    -- looked", and dispatch resolves it then.
    subzone_id  BIGINT        NULL REFERENCES delivery_subzones (id),
    -- A person placed this address by hand. The map cannot know that a house
    -- sits on the wrong side of a boundary road, or that a colony's only
    -- usable gate opens into the next territory; when somebody says so it
    -- outranks the polygons, and nothing automatic may move it again. It
    -- outranks them for THIS shop only.
    locked      BOOLEAN   NOT NULL DEFAULT FALSE,
    -- THE POINT THE ANSWER WAS RESOLVED FROM, so a stamp can say whether it is
    -- still about where this house is. A customer who corrects a pin that was
    -- two streets out has moved the house in every shop's map at once; each
    -- shop's stamp then describes a place the customer says is wrong, and
    -- every shop finds that out from its own row rather than from whichever
    -- shop happened to handle the edit.
    stamped_latitude  DOUBLE PRECISION NULL,
    stamped_longitude DOUBLE PRECISION NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP     NULL
);

-- HIBERNATE MAY HAVE MADE THIS TABLE FIRST, and on a deployment where it did
-- (see FlywayAfterSchemaConfig: ddl-auto owns the tables here, migrations
-- supplement them) the CREATE above is a no-op. The constraint is therefore
-- added separately and idempotently rather than inline, or a database that
-- already has the table never gets it - and "one stamp per shop per address"
-- is the whole shape of the fix.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uk_address_territory_stamp'
    ) THEN
        ALTER TABLE address_territory_stamps
            ADD CONSTRAINT uk_address_territory_stamp UNIQUE (shop_id, address_id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_address_stamp_shop_address
    ON address_territory_stamps (shop_id, address_id);
CREATE INDEX IF NOT EXISTS idx_address_stamp_subzone
    ON address_territory_stamps (subzone_id) WHERE subzone_id IS NOT NULL;

-- CARRYING THE EXISTING STAMPS ACROSS, to the shop that actually owns them.
--
-- Every stamped address today points at exactly one subzone, and that subzone
-- belongs to exactly one shop - so the shop each existing stamp belongs to is
-- not a guess, it is a join. A single-shop deployment therefore comes out of
-- this migration with its stamps unchanged and its pins intact.
--
-- Addresses with no subzone are deliberately NOT backfilled: under the old
-- column, "no subzone" meant "nobody has resolved this yet" for every shop
-- at once, and that is exactly what "no row" means here.
INSERT INTO address_territory_stamps (shop_id, address_id, subzone_id, locked,
                                      stamped_latitude, stamped_longitude, created_at)
SELECT s.shop_id, a.id, a.subzone_id, COALESCE(a.subzone_locked, FALSE),
       a.latitude, a.longitude, NOW()
FROM addresses a
JOIN delivery_subzones s ON s.id = a.subzone_id
WHERE s.shop_id IS NOT NULL
  -- Re-runnable: WHERE NOT EXISTS rather than ON CONFLICT, so this does not
  -- depend on the constraint above having been the one that created it.
  AND NOT EXISTS (
      SELECT 1 FROM address_territory_stamps t
      WHERE t.shop_id = s.shop_id AND t.address_id = a.id
  );

-- THE OLD COLUMNS ARE LEFT IN PLACE ON PURPOSE, and nothing reads or writes
-- them from this release onwards (AddressStampHasOneOwnerTest fails the build
-- if anything starts again). They are the rollback path for this deploy: the
-- previous release reads them, and dropping them in the same migration that
-- moves the data would make going back a data-loss event. They come out in a
-- separate migration once this release has been running.
COMMENT ON COLUMN addresses.subzone_id IS
    'SUPERSEDED by address_territory_stamps (V70). Not read or written. Dropped in a later migration.';
COMMENT ON COLUMN addresses.subzone_locked IS
    'SUPERSEDED by address_territory_stamps.locked (V70). Not read or written. Dropped in a later migration.';
