-- A VARIANT IS WHATEVER TELLS TWO SELLABLE THINGS APART, AND A DEPARTMENT
-- CAN BELONG TO ONE SHOP.
--
-- Two things a real device proved were missing, both additive, neither one
-- touching a row that already exists.
--
-- ============================================================ 1. ATTRIBUTES
--
-- product_variants describes a variant with `quantity` and `unit`: 1 and "kg",
-- 500 and "g". That is a grocer's shelf written into a schema, and GP-STORE
-- stopped being only a grocer's shelf. A phone has 8 GB of RAM and 128 GB of
-- storage and comes in black; a saree is red, silk and Banarasi; a shoe is a
-- size 9. None of those is a pack size, and the merchant admin app was asking
-- a phone shop to type "8" into a box labelled "Pack size" and
-- "8 gb and 128 gb" into one labelled "Unit (kg, g, L...)".
--
-- NAME/VALUE PAIRS RATHER THAN COLUMNS, because the alternative is a column
-- per trade and a migration every time GP-STORE admits a new one. Hardware
-- needs a thread pitch, medicine needs a strength, a restaurant needs "Half"
-- and "Full". A table of pairs holds all of them and needs no schema change
-- for the next trade after those.
--
-- quantity AND unit ARE KEPT AND STILL WORK. Every grocery variant on Shop #1
-- goes on meaning exactly what it meant before this migration - nothing reads
-- them differently, nothing backfills them, and a variant with no attribute
-- rows is a completely normal variant. OrderWeightCalculator still reads the
-- pack size to weigh a basket. Attributes are what a variant can ALSO have.
CREATE TABLE IF NOT EXISTS product_variant_attributes (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_variant_id BIGINT       NOT NULL REFERENCES product_variants (id) ON DELETE CASCADE,
    -- What the merchant is describing: "RAM", "Storage", "Colour", "Size",
    -- "Material", "Strength". Free text on purpose - see above.
    name               VARCHAR(60)  NOT NULL,
    -- What it is: "8 GB", "128 GB", "Black", "9", "Silk", "500 mg".
    value              VARCHAR(160) NOT NULL,
    -- The order the merchant put them in, which is the order a customer reads
    -- them. RAM before Storage before Colour is information, not decoration.
    display_order      INTEGER      NOT NULL DEFAULT 0,
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ONE VALUE PER ATTRIBUTE NAME PER VARIANT. A variant with two rows both
-- called "RAM" has no answer to "how much RAM", and the screen would show
-- whichever the database happened to return first. Case-insensitive because
-- "RAM" and "ram" are the same question asked twice.
--
-- A FUNCTIONAL UNIQUE INDEX, NOT A TABLE CONSTRAINT, because lower(name) is an
-- expression. Hibernate cannot express it either, which is why it is only
-- here and not on the entity - and why CREATE UNIQUE INDEX IF NOT EXISTS is
-- enough on its own without the guarded DO block V70 needed for a constraint.
CREATE UNIQUE INDEX IF NOT EXISTS ux_variant_attribute_name
    ON product_variant_attributes (product_variant_id, lower(name));

CREATE INDEX IF NOT EXISTS idx_variant_attribute_variant
    ON product_variant_attributes (product_variant_id, display_order);

-- ======================================================== 2. SHOP CATEGORIES
--
-- categories is the PLATFORM's taxonomy: one tree every shop picks from, and
-- renaming a row in it renames it for every merchant on GP-STORE. That is why
-- writing to it needs CATALOG_DEFINE once a second shop exists.
--
-- It left a merchant with nowhere to put "charger". The merchant admin app
-- offers an Add Category button, the button posts to the platform tree, and a
-- phone shop tapping it was told "You don't have permission to do that" - a
-- UI promising something the authorization contract refuses.
--
-- A SHOP CATEGORY IS THE SHOP'S OWN DEPARTMENT. It is shop-owned, so the
-- ordinary tenant filter narrows every read to the shop asking: Deepak Phone
-- Shop creating "charger" does not put "charger" on GUPT SAREE's screen, and
-- does not add a row that every customer's category tree then shows.
--
-- global_category_id IS THE BRIDGE, and it is optional. A shop that is simply
-- organising its own shelf leaves it null. A shop that is ENABLING an existing
-- platform department - "I sell Medicine" - points at that row, which is how a
-- shop-local department and the shared tree stay one concept rather than two
-- competing ones. It also gives the platform a controlled way to promote a
-- shop's word into the official taxonomy later: set the link, keep the row.
CREATE TABLE IF NOT EXISTS shop_categories (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id            BIGINT       NOT NULL REFERENCES shops (id),
    name               VARCHAR(120) NOT NULL,
    description        VARCHAR(500),
    -- Optional link to the platform taxonomy. NULL means "this department is
    -- purely this shop's own".
    global_category_id BIGINT       REFERENCES categories (id),
    display_order      INTEGER,
    active             BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ONE DEPARTMENT OF A GIVEN NAME PER SHOP - and per SHOP, which is the point.
-- Two merchants may both sell chargers and both call the department "charger";
-- neither takes the word away from the other. Case-insensitive so "Charger"
-- typed on Tuesday does not become a second department beside "charger".
CREATE UNIQUE INDEX IF NOT EXISTS ux_shop_category_name
    ON shop_categories (shop_id, lower(name));

CREATE INDEX IF NOT EXISTS idx_shop_category_shop
    ON shop_categories (shop_id, active);

-- WHICH OF ITS OWN DEPARTMENTS A SHOP FILED A LISTING UNDER.
--
-- Nullable, and null is the normal state: a listing with no shop department is
-- found through the platform category of the product behind it, exactly as
-- every listing was before this migration. This column only says "and the
-- merchant also put it on this shelf of their own".
--
-- ON THE LISTING RATHER THAN ON THE VARIANT, because it is merchandising and
-- merchandising is the shop's. Two shops selling the same charger may file it
-- under different departments and neither is wrong.
ALTER TABLE shop_product_variants
    ADD COLUMN IF NOT EXISTS shop_category_id BIGINT REFERENCES shop_categories (id);

CREATE INDEX IF NOT EXISTS idx_shop_product_variant_shop_category
    ON shop_product_variants (shop_category_id);

COMMENT ON TABLE product_variant_attributes IS
    'Generic name/value description of a variant (RAM, Storage, Colour, Size, '
    'Material, Strength). Additive: product_variants.quantity/unit remain the '
    'grocery pack size and are unchanged.';

COMMENT ON TABLE shop_categories IS
    'A department belonging to ONE shop. Shop-owned, so the tenant filter '
    'narrows every read. categories remains the platform taxonomy and is '
    'writable only with CATALOG_DEFINE.';
