"""
The product universe GP-Store's test catalog is generated from.

WHY THIS IS A SPEC RATHER THAN A THOUSAND HAND-TYPED ROWS: a flat list of a
thousand products cannot be reviewed. A list of real brand/product/pack
combinations can be - a reader can see at a glance that Aashirvaad makes atta
and not shampoo, which is the only thing that makes the catalogue believable.
The generator expands (brand x product x pack) into rows and prices them by
category, so correcting one wrong fact here fixes every row it produced.

EVERY PRICE IS ASSUMED. Nothing here was read off a shelf or a website. The
base rates below are plausible Indian retail rates per unit as of 2026 and are
seeded as is_test_data = true, price_verified = false.
"""

# (category, subcategory, brand, product name stem, [(qty, unit)], base rate per base unit in rupees)
# base unit: kg for kg/g, L for l/ml, piece for pcs.

CATALOG = [
 # ---------------- 1. Atta, Rice & Dal ----------------
 ("Atta, Rice & Dal","Atta","Aashirvaad","Shudh Chakki Atta",[(1,"kg"),(5,"kg"),(10,"kg")],62),
 ("Atta, Rice & Dal","Atta","Aashirvaad","Select Sharbati Atta",[(5,"kg"),(10,"kg")],78),
 ("Atta, Rice & Dal","Atta","Aashirvaad","Multigrain Atta",[(5,"kg")],85),
 ("Atta, Rice & Dal","Atta","Fortune","Chakki Fresh Atta",[(1,"kg"),(5,"kg"),(10,"kg")],58),
 ("Atta, Rice & Dal","Atta","Pillsbury","Chakki Fresh Atta",[(1,"kg"),(5,"kg")],60),
 ("Atta, Rice & Dal","Atta","Patanjali","Whole Wheat Atta",[(1,"kg"),(5,"kg")],55),
 ("Atta, Rice & Dal","Atta","Tata Sampann","Besan",[(500,"g"),(1,"kg")],120),
 ("Atta, Rice & Dal","Atta","Rajdhani","Besan",[(500,"g"),(1,"kg")],110),
 ("Atta, Rice & Dal","Atta","Aashirvaad","Maida",[(500,"g"),(1,"kg")],48),
 ("Atta, Rice & Dal","Atta","Aashirvaad","Sooji Rava",[(500,"g"),(1,"kg")],52),
 ("Atta, Rice & Dal","Rice","India Gate","Basmati Rice Classic",[(1,"kg"),(5,"kg")],165),
 ("Atta, Rice & Dal","Rice","India Gate","Basmati Rice Feast Rozana",[(1,"kg"),(5,"kg")],95),
 ("Atta, Rice & Dal","Rice","Daawat","Rozana Basmati Rice",[(1,"kg"),(5,"kg")],92),
 ("Atta, Rice & Dal","Rice","Daawat","Devaaya Basmati Rice",[(1,"kg"),(5,"kg")],140),
 ("Atta, Rice & Dal","Rice","Fortune","Everyday Basmati Rice",[(1,"kg"),(5,"kg")],88),
 ("Atta, Rice & Dal","Rice","Tata Sampann","Sona Masoori Rice",[(1,"kg"),(5,"kg")],72),
 ("Atta, Rice & Dal","Rice","Kohinoor","Basmati Rice Authentic",[(1,"kg"),(5,"kg")],158),
 ("Atta, Rice & Dal","Rice","Patanjali","Brown Rice",[(1,"kg")],90),
 ("Atta, Rice & Dal","Rice","Fortune","Idli Rice",[(5,"kg")],62),
 ("Atta, Rice & Dal","Pulses","Tata Sampann","Toor Dal Unpolished",[(500,"g"),(1,"kg")],175),
 ("Atta, Rice & Dal","Pulses","Tata Sampann","Moong Dal Unpolished",[(500,"g"),(1,"kg")],150),
 ("Atta, Rice & Dal","Pulses","Tata Sampann","Chana Dal Unpolished",[(500,"g"),(1,"kg")],95),
 ("Atta, Rice & Dal","Pulses","Tata Sampann","Urad Dal Unpolished",[(500,"g"),(1,"kg")],160),
 ("Atta, Rice & Dal","Pulses","Tata Sampann","Masoor Dal Unpolished",[(500,"g"),(1,"kg")],110),
 ("Atta, Rice & Dal","Pulses","Fortune","Toor Dal",[(1,"kg")],168),
 ("Atta, Rice & Dal","Pulses","Fortune","Moong Dal",[(1,"kg")],145),
 ("Atta, Rice & Dal","Pulses","Fortune","Chana Dal",[(1,"kg")],92),
 ("Atta, Rice & Dal","Pulses","Rajdhani","Rajma Chitra",[(500,"g"),(1,"kg")],165),
 ("Atta, Rice & Dal","Pulses","Rajdhani","Kabuli Chana",[(500,"g"),(1,"kg")],130),
 ("Atta, Rice & Dal","Pulses","Rajdhani","Kala Chana",[(500,"g"),(1,"kg")],105),
 ("Atta, Rice & Dal","Pulses","Rajdhani","Moth Dal",[(500,"g")],120),
 ("Atta, Rice & Dal","Pulses","Patanjali","Arhar Dal",[(1,"kg")],162),
 ("Atta, Rice & Dal","Poha & Sabudana","Patanjali","Poha",[(500,"g")],56),
 ("Atta, Rice & Dal","Poha & Sabudana","Tata Sampann","Sabudana",[(500,"g")],90),

 # ---------------- 2. Oils & Ghee ----------------
 ("Oils & Ghee","Cooking Oil","Fortune","Sunlite Refined Sunflower Oil",[(1,"l"),(5,"l")],150),
 ("Oils & Ghee","Cooking Oil","Fortune","Soya Health Refined Oil",[(1,"l"),(5,"l")],135),
 ("Oils & Ghee","Cooking Oil","Fortune","Kachi Ghani Mustard Oil",[(1,"l"),(5,"l")],165),
 ("Oils & Ghee","Cooking Oil","Fortune","Rice Bran Health Oil",[(1,"l"),(5,"l")],158),
 ("Oils & Ghee","Cooking Oil","Saffola","Gold Refined Oil",[(1,"l"),(5,"l")],185),
 ("Oils & Ghee","Cooking Oil","Saffola","Active Refined Oil",[(1,"l"),(5,"l")],175),
 ("Oils & Ghee","Cooking Oil","Saffola","Tasty Refined Oil",[(1,"l"),(5,"l")],168),
 ("Oils & Ghee","Cooking Oil","Dhara","Refined Sunflower Oil",[(1,"l")],148),
 ("Oils & Ghee","Cooking Oil","Dhara","Kachi Ghani Mustard Oil",[(1,"l")],162),
 ("Oils & Ghee","Cooking Oil","Patanjali","Kachi Ghani Mustard Oil",[(1,"l")],170),
 ("Oils & Ghee","Cooking Oil","Gemini","Refined Sunflower Oil",[(1,"l")],145),
 ("Oils & Ghee","Cooking Oil","Sundrop","Heart Refined Oil",[(1,"l")],178),
 ("Oils & Ghee","Coconut & Specialty Oil","Parachute","Coconut Oil",[(200,"ml"),(500,"ml"),(1,"l")],320),
 ("Oils & Ghee","Coconut & Specialty Oil","Patanjali","Virgin Coconut Oil",[(500,"ml")],420),
 ("Oils & Ghee","Ghee","Amul","Pure Ghee",[(500,"ml"),(1,"l")],640),
 ("Oils & Ghee","Ghee","Patanjali","Cow Ghee",[(500,"ml"),(1,"l")],700),
 ("Oils & Ghee","Ghee","Mother Dairy","Cow Ghee",[(500,"ml"),(1,"l")],650),
 ("Oils & Ghee","Ghee","Nandini","Pure Ghee",[(500,"ml"),(1,"l")],620),
 ("Oils & Ghee","Ghee","Milky Mist","Cow Ghee",[(500,"ml"),(1,"l")],680),
 ("Oils & Ghee","Vanaspati","Dalda","Vanaspati",[(1,"l")],155),

 # ---------------- 3. Masala & Spices ----------------
 ("Masala & Spices","Ground Spices","MDH","Deggi Mirch",[(100,"g"),(500,"g")],900),
 ("Masala & Spices","Ground Spices","MDH","Haldi Powder",[(100,"g"),(500,"g")],400),
 ("Masala & Spices","Ground Spices","MDH","Dhania Powder",[(100,"g"),(500,"g")],380),
 ("Masala & Spices","Ground Spices","Everest","Turmeric Powder",[(100,"g"),(200,"g"),(500,"g")],390),
 ("Masala & Spices","Ground Spices","Everest","Red Chilli Powder",[(100,"g"),(200,"g"),(500,"g")],620),
 ("Masala & Spices","Ground Spices","Everest","Coriander Powder",[(100,"g"),(500,"g")],370),
 ("Masala & Spices","Ground Spices","Catch","Red Chilli Powder",[(100,"g"),(200,"g")],640),
 ("Masala & Spices","Ground Spices","Catch","Turmeric Powder",[(100,"g"),(200,"g")],400),
 ("Masala & Spices","Ground Spices","Tata Sampann","Turmeric Powder",[(100,"g"),(200,"g")],420),
 ("Masala & Spices","Ground Spices","Tata Sampann","Chilli Powder",[(100,"g"),(200,"g")],660),
 ("Masala & Spices","Ground Spices","Tata Sampann","Coriander Powder",[(100,"g"),(200,"g")],390),
 ("Masala & Spices","Blended Masala","MDH","Garam Masala",[(50,"g"),(100,"g")],1400),
 ("Masala & Spices","Blended Masala","MDH","Chana Masala",[(100,"g")],900),
 ("Masala & Spices","Blended Masala","MDH","Sabji Masala",[(100,"g")],880),
 ("Masala & Spices","Blended Masala","MDH","Chaat Masala",[(100,"g")],820),
 ("Masala & Spices","Blended Masala","MDH","Kitchen King Masala",[(100,"g")],1100),
 ("Masala & Spices","Blended Masala","Everest","Garam Masala",[(50,"g"),(100,"g")],1350),
 ("Masala & Spices","Blended Masala","Everest","Chhole Masala",[(100,"g")],880),
 ("Masala & Spices","Blended Masala","Everest","Kitchen King",[(100,"g")],1080),
 ("Masala & Spices","Blended Masala","Everest","Pav Bhaji Masala",[(100,"g")],920),
 ("Masala & Spices","Blended Masala","Everest","Sambhar Masala",[(100,"g")],860),
 ("Masala & Spices","Blended Masala","Catch","Garam Masala",[(100,"g")],1300),
 ("Masala & Spices","Blended Masala","Aachi","Sambar Powder",[(100,"g"),(200,"g")],700),
 ("Masala & Spices","Blended Masala","Aachi","Rasam Powder",[(100,"g"),(200,"g")],700),
 ("Masala & Spices","Blended Masala","Aachi","Chicken Masala",[(100,"g")],860),
 ("Masala & Spices","Blended Masala","Aachi","Biryani Masala",[(100,"g")],880),
 ("Masala & Spices","Whole Spices","Catch","Black Pepper Whole",[(100,"g")],2400),
 ("Masala & Spices","Whole Spices","Tata Sampann","Jeera Whole",[(100,"g"),(200,"g")],700),
 ("Masala & Spices","Whole Spices","Everest","Elaichi Green",[(25,"g"),(50,"g")],4200),
 ("Masala & Spices","Whole Spices","Tata Sampann","Saunf",[(100,"g")],520),
 ("Masala & Spices","Whole Spices","Tata Sampann","Methi Seeds",[(100,"g")],300),
 ("Masala & Spices","Whole Spices","Tata Sampann","Rai Sarson",[(100,"g")],320),
 ("Masala & Spices","Whole Spices","Catch","Bay Leaf Tej Patta",[(50,"g")],600),
 ("Masala & Spices","Whole Spices","Catch","Cloves Laung",[(50,"g")],3600),
 ("Masala & Spices","Whole Spices","Catch","Cinnamon Dalchini",[(50,"g")],1600),
 ("Masala & Spices","Hing & Others","Everest","Hing Compounded Asafoetida",[(50,"g")],3000),
 ("Masala & Spices","Hing & Others","Catch","Hing Powder",[(50,"g")],2900),

 # ---------------- 4. Salt & Sugar ----------------
 ("Salt & Sugar","Salt","Tata","Salt Iodised",[(1,"kg")],28),
 ("Salt & Sugar","Salt","Tata","Salt Lite",[(1,"kg")],48),
 ("Salt & Sugar","Salt","Tata","Rock Salt Sendha Namak",[(1,"kg")],60),
 ("Salt & Sugar","Salt","Tata","Black Salt Kala Namak",[(1,"kg")],62),
 ("Salt & Sugar","Salt","Aashirvaad","Salt Iodised",[(1,"kg")],28),
 ("Salt & Sugar","Salt","Patanjali","Saindhava Lavana Salt",[(1,"kg")],58),
 ("Salt & Sugar","Sugar","Madhur","Pure Sugar",[(1,"kg"),(5,"kg")],52),
 ("Salt & Sugar","Sugar","Dhampure","Speciality Sugar",[(1,"kg")],58),
 ("Salt & Sugar","Sugar","Tata","Sugar Refined",[(1,"kg")],54),
 ("Salt & Sugar","Jaggery & Sweeteners","Patanjali","Jaggery Gur",[(500,"g"),(1,"kg")],80),
 ("Salt & Sugar","Jaggery & Sweeteners","Dabur","Honey",[(250,"g"),(500,"g"),(1,"kg")],440),
 ("Salt & Sugar","Jaggery & Sweeteners","Patanjali","Honey",[(250,"g"),(500,"g")],400),
 ("Salt & Sugar","Jaggery & Sweeteners","Sugar Free","Gold Sweetener",[(100,"pcs")],2.2),

 # ---------------- 5. Biscuits & Bakery ----------------
 ("Biscuits & Bakery","Glucose & Marie","Parle","Parle-G Original Gluco Biscuits",[(50,"g"),(250,"g"),(800,"g")],52),
 ("Biscuits & Bakery","Glucose & Marie","Britannia","Tiger Glucose Biscuits",[(100,"g"),(250,"g")],50),
 ("Biscuits & Bakery","Glucose & Marie","Britannia","Marie Gold Biscuits",[(120,"g"),(250,"g")],72),
 ("Biscuits & Bakery","Glucose & Marie","Sunfeast","Marie Light Biscuits",[(120,"g"),(250,"g")],70),
 ("Biscuits & Bakery","Glucose & Marie","Patanjali","Doodh Biscuit",[(200,"g")],60),
 ("Biscuits & Bakery","Cream Biscuits","Britannia","Bourbon Chocolate Cream",[(100,"g"),(300,"g")],110),
 ("Biscuits & Bakery","Cream Biscuits","Britannia","Jim Jam Cream Biscuits",[(150,"g")],105),
 ("Biscuits & Bakery","Cream Biscuits","Sunfeast","Bounce Elaichi Cream",[(100,"g"),(250,"g")],95),
 ("Biscuits & Bakery","Cream Biscuits","Parle","Hide & Seek Chocolate Chip",[(100,"g"),(200,"g")],140),
 ("Biscuits & Bakery","Cream Biscuits","Parle","Krackjack Sweet & Salty",[(100,"g"),(250,"g")],72),
 ("Biscuits & Bakery","Cream Biscuits","Parle","Monaco Salted Biscuits",[(100,"g"),(200,"g")],78),
 ("Biscuits & Bakery","Cream Biscuits","Oreo","Chocolate Cream Biscuits",[(120,"g")],150),
 ("Biscuits & Bakery","Digestive & Health","Britannia","NutriChoice Digestive",[(200,"g"),(400,"g")],125),
 ("Biscuits & Bakery","Digestive & Health","Sunfeast","Farmlite Digestive Oats",[(150,"g")],130),
 ("Biscuits & Bakery","Digestive & Health","Patanjali","Marie Biscuit",[(250,"g")],62),
 ("Biscuits & Bakery","Cookies","Britannia","Good Day Cashew Cookies",[(100,"g"),(250,"g")],105),
 ("Biscuits & Bakery","Cookies","Britannia","Good Day Butter Cookies",[(100,"g"),(250,"g")],100),
 ("Biscuits & Bakery","Cookies","Sunfeast","Dark Fantasy Choco Fills",[(75,"g"),(150,"g")],220),
 ("Biscuits & Bakery","Rusk & Bread","Britannia","Premium Bake Rusk",[(200,"g"),(400,"g")],85),
 ("Biscuits & Bakery","Rusk & Bread","Parle","Rusk Elaichi",[(300,"g")],80),
 ("Biscuits & Bakery","Rusk & Bread","Britannia","Brown Bread",[(400,"g")],125),
 ("Biscuits & Bakery","Rusk & Bread","Britannia","Sandwich White Bread",[(400,"g")],110),
 ("Biscuits & Bakery","Rusk & Bread","Britannia","Pav Bread",[(300,"g")],110),

 # ---------------- 6. Snacks & Namkeen ----------------
 ("Snacks & Namkeen","Chips & Crisps","Lay's","Classic Salted Potato Chips",[(52,"g"),(90,"g")],440),
 ("Snacks & Namkeen","Chips & Crisps","Lay's","India's Magic Masala Chips",[(52,"g"),(90,"g")],440),
 ("Snacks & Namkeen","Chips & Crisps","Lay's","American Style Cream & Onion",[(52,"g"),(90,"g")],440),
 ("Snacks & Namkeen","Chips & Crisps","Bingo","Mad Angles Achaari Masti",[(66,"g"),(90,"g")],420),
 ("Snacks & Namkeen","Chips & Crisps","Bingo","Tedhe Medhe Masala Tadka",[(60,"g")],400),
 ("Snacks & Namkeen","Chips & Crisps","Kurkure","Masala Munch",[(70,"g"),(90,"g")],400),
 ("Snacks & Namkeen","Chips & Crisps","Kurkure","Green Chutney Rajasthani Style",[(70,"g")],400),
 ("Snacks & Namkeen","Chips & Crisps","Too Yumm","Multigrain Chips Chilli Achaari",[(50,"g")],600),
 ("Snacks & Namkeen","Chips & Crisps","Too Yumm","Karare Masala Munchies",[(48,"g")],580),
 ("Snacks & Namkeen","Chips & Crisps","Uncle Chipps","Spicy Treat",[(52,"g")],420),
 ("Snacks & Namkeen","Namkeen","Haldiram's","Aloo Bhujia",[(200,"g"),(400,"g")],250),
 ("Snacks & Namkeen","Namkeen","Haldiram's","Bhujia Sev",[(200,"g"),(400,"g")],250),
 ("Snacks & Namkeen","Namkeen","Haldiram's","Navratan Mixture",[(200,"g"),(400,"g")],255),
 ("Snacks & Namkeen","Namkeen","Haldiram's","Moong Dal",[(200,"g")],290),
 ("Snacks & Namkeen","Namkeen","Haldiram's","Khatta Meetha",[(200,"g"),(400,"g")],250),
 ("Snacks & Namkeen","Namkeen","Haldiram's","Chana Chur",[(200,"g")],245),
 ("Snacks & Namkeen","Namkeen","Bikano","Bikaneri Bhujia",[(200,"g"),(400,"g")],235),
 ("Snacks & Namkeen","Namkeen","Bikano","Navratan Mix",[(200,"g")],240),
 ("Snacks & Namkeen","Namkeen","Balaji","Ratlami Sev",[(200,"g")],230),
 ("Snacks & Namkeen","Namkeen","Patanjali","Soan Papdi",[(250,"g"),(500,"g")],240),
 ("Snacks & Namkeen","Popcorn & Extruded","Act II","Butter Delite Popcorn",[(70,"g")],400),
 ("Snacks & Namkeen","Popcorn & Extruded","Cornitos","Nacho Crisps Sea Salt",[(60,"g")],830),

 # ---------------- 7. Tea, Coffee & Milk Drinks ----------------
 ("Tea, Coffee & Milk Drinks","Tea","Tata","Tea Gold",[(250,"g"),(500,"g"),(1,"kg")],580),
 ("Tea, Coffee & Milk Drinks","Tea","Tata","Tea Premium",[(250,"g"),(500,"g"),(1,"kg")],480),
 ("Tea, Coffee & Milk Drinks","Tea","Tata","Tea Agni",[(250,"g"),(500,"g")],320),
 ("Tea, Coffee & Milk Drinks","Tea","Brooke Bond","Red Label Tea",[(250,"g"),(500,"g"),(1,"kg")],520),
 ("Tea, Coffee & Milk Drinks","Tea","Brooke Bond","Taaza Tea",[(250,"g"),(500,"g")],400),
 ("Tea, Coffee & Milk Drinks","Tea","Taj Mahal","Rich Aroma Tea",[(250,"g"),(500,"g")],680),
 ("Tea, Coffee & Milk Drinks","Tea","Society","Masala Tea",[(250,"g"),(500,"g")],500),
 ("Tea, Coffee & Milk Drinks","Tea","Wagh Bakri","Premium Leaf Tea",[(250,"g"),(500,"g")],540),
 ("Tea, Coffee & Milk Drinks","Tea","Lipton","Green Tea Natural",[(25,"pcs")],8),
 ("Tea, Coffee & Milk Drinks","Tea","Tetley","Green Tea Lemon Honey",[(25,"pcs")],8),
 ("Tea, Coffee & Milk Drinks","Coffee","Nescafé","Classic Instant Coffee",[(50,"g"),(100,"g"),(200,"g")],3400),
 ("Tea, Coffee & Milk Drinks","Coffee","Nescafé","Sunrise Instant Coffee",[(50,"g"),(100,"g")],2600),
 ("Tea, Coffee & Milk Drinks","Coffee","Bru","Instant Coffee",[(50,"g"),(100,"g")],2900),
 ("Tea, Coffee & Milk Drinks","Coffee","Bru","Gold Instant Coffee",[(50,"g"),(100,"g")],3600),
 ("Tea, Coffee & Milk Drinks","Coffee","Continental","Malgudi Filter Coffee",[(200,"g"),(500,"g")],900),
 ("Tea, Coffee & Milk Drinks","Milk Drinks","Bournvita","Health Drink",[(500,"g"),(1,"kg")],480),
 ("Tea, Coffee & Milk Drinks","Milk Drinks","Horlicks","Classic Malt Health Drink",[(500,"g"),(1,"kg")],520),
 ("Tea, Coffee & Milk Drinks","Milk Drinks","Boost","Health Drink",[(500,"g"),(1,"kg")],500),
 ("Tea, Coffee & Milk Drinks","Milk Drinks","Complan","Royale Chocolate",[(500,"g")],620),
 ("Tea, Coffee & Milk Drinks","Milk Drinks","Nestlé","Milo Activ-Go",[(400,"g")],480),

 # ---------------- 8. Dairy & Eggs ----------------
 ("Dairy & Eggs","Milk","Amul","Taaza Toned Milk",[(500,"ml"),(1,"l")],56),
 ("Dairy & Eggs","Milk","Amul","Gold Full Cream Milk",[(500,"ml"),(1,"l")],68),
 ("Dairy & Eggs","Milk","Amul","Slim n Trim Skimmed Milk",[(500,"ml"),(1,"l")],52),
 ("Dairy & Eggs","Milk","Mother Dairy","Toned Milk",[(500,"ml"),(1,"l")],56),
 ("Dairy & Eggs","Milk","Mother Dairy","Full Cream Milk",[(500,"ml"),(1,"l")],68),
 ("Dairy & Eggs","Milk","Nandini","Toned Milk",[(500,"ml"),(1,"l")],48),
 ("Dairy & Eggs","Milk","Milky Mist","Toned Milk",[(1,"l")],62),
 ("Dairy & Eggs","Butter & Cheese","Amul","Butter Pasteurised",[(100,"g"),(500,"g")],580),
 ("Dairy & Eggs","Butter & Cheese","Amul","Cheese Slices",[(200,"g")],700),
 ("Dairy & Eggs","Butter & Cheese","Amul","Cheese Block",[(200,"g"),(400,"g")],660),
 ("Dairy & Eggs","Butter & Cheese","Amul","Cheese Spread Plain",[(200,"g")],600),
 ("Dairy & Eggs","Butter & Cheese","Mother Dairy","Butter",[(100,"g"),(500,"g")],575),
 ("Dairy & Eggs","Butter & Cheese","Milky Mist","Cheese Slices",[(200,"g")],720),
 ("Dairy & Eggs","Curd & Paneer","Amul","Masti Dahi",[(400,"g"),(1,"kg")],80),
 ("Dairy & Eggs","Curd & Paneer","Mother Dairy","Classic Dahi",[(400,"g"),(1,"kg")],80),
 ("Dairy & Eggs","Curd & Paneer","Milky Mist","Curd",[(400,"g"),(1,"kg")],85),
 ("Dairy & Eggs","Curd & Paneer","Amul","Malai Paneer",[(200,"g"),(500,"g")],400),
 ("Dairy & Eggs","Curd & Paneer","Milky Mist","Paneer",[(200,"g"),(500,"g")],420),
 ("Dairy & Eggs","Curd & Paneer","Mother Dairy","Paneer",[(200,"g")],410),
 ("Dairy & Eggs","Cream & Condensed","Amul","Fresh Cream",[(250,"ml")],320),
 ("Dairy & Eggs","Cream & Condensed","Nestlé","Milkmaid Condensed Milk",[(400,"g")],390),
 ("Dairy & Eggs","Cream & Condensed","Amul","Mithai Mate",[(400,"g")],370),
 ("Dairy & Eggs","Buttermilk & Lassi","Amul","Masti Chaas",[(200,"ml"),(1,"l")],50),
 ("Dairy & Eggs","Buttermilk & Lassi","Mother Dairy","Lassi",[(200,"ml")],125),
 ("Dairy & Eggs","Eggs","Suguna","Farm Fresh Eggs",[(6,"pcs"),(12,"pcs")],8),
 ("Dairy & Eggs","Eggs","Keggfarms","Kegg Eggs",[(6,"pcs")],13),

 # ---------------- 9. Instant Food & Noodles ----------------
 ("Instant Food & Noodles","Noodles","Maggi","2-Minute Masala Noodles",[(70,"g"),(280,"g"),(560,"g")],200),
 ("Instant Food & Noodles","Noodles","Maggi","Atta Masala Noodles",[(75,"g"),(300,"g")],220),
 ("Instant Food & Noodles","Noodles","Maggi","Oats Masala Noodles",[(72,"g")],240),
 ("Instant Food & Noodles","Noodles","Yippee","Magic Masala Noodles",[(70,"g"),(280,"g")],195),
 ("Instant Food & Noodles","Noodles","Top Ramen","Curry Veg Noodles",[(70,"g")],190),
 ("Instant Food & Noodles","Noodles","Knorr","Soupy Noodles Chinese",[(70,"g")],215),
 ("Instant Food & Noodles","Pasta & Vermicelli","Maggi","Pazzta Cheese Macaroni",[(70,"g")],300),
 ("Instant Food & Noodles","Pasta & Vermicelli","Bambino","Vermicelli Roasted",[(400,"g")],110),
 ("Instant Food & Noodles","Pasta & Vermicelli","MTR","Vermicelli",[(440,"g")],115),
 ("Instant Food & Noodles","Pasta & Vermicelli","Sunfeast","YiPPee Pasta Masala",[(65,"g")],290),
 ("Instant Food & Noodles","Soups","Knorr","Classic Sweet Corn Soup",[(44,"g")],1150),
 ("Instant Food & Noodles","Soups","Knorr","Hot & Sour Veg Soup",[(43,"g")],1150),
 ("Instant Food & Noodles","Soups","Maggi","Rich Tomato Soup",[(53,"g")],1000),
 ("Instant Food & Noodles","Ready Mixes","MTR","Rava Idli Mix",[(500,"g")],180),
 ("Instant Food & Noodles","Ready Mixes","MTR","Gulab Jamun Mix",[(500,"g")],200),
 ("Instant Food & Noodles","Ready Mixes","Gits","Dhokla Mix",[(200,"g")],400),
 ("Instant Food & Noodles","Ready Mixes","Gits","Idli Mix",[(200,"g")],380),
 ("Instant Food & Noodles","Ready Mixes","Aashirvaad","Instant Poha",[(180,"g")],330),

 # ---------------- 10. Beverages ----------------
 ("Beverages","Soft Drinks","Thums Up","Soft Drink",[(750,"ml"),(1.25,"l"),(2,"l")],48),
 ("Beverages","Soft Drinks","Coca-Cola","Soft Drink",[(750,"ml"),(1.25,"l"),(2,"l")],48),
 ("Beverages","Soft Drinks","Sprite","Lime Flavoured Soft Drink",[(750,"ml"),(1.25,"l"),(2,"l")],48),
 ("Beverages","Soft Drinks","Fanta","Orange Soft Drink",[(750,"ml"),(1.25,"l")],48),
 ("Beverages","Soft Drinks","Limca","Soft Drink",[(750,"ml"),(1.25,"l")],48),
 ("Beverages","Soft Drinks","Pepsi","Soft Drink",[(750,"ml"),(1.25,"l"),(2,"l")],48),
 ("Beverages","Soft Drinks","Mountain Dew","Soft Drink",[(750,"ml"),(1.25,"l")],48),
 ("Beverages","Soft Drinks","7Up","Lemon Soft Drink",[(750,"ml"),(1.25,"l")],48),
 ("Beverages","Juices & Nectars","Real","Mixed Fruit Juice",[(1,"l")],125),
 ("Beverages","Juices & Nectars","Real","Orange Juice",[(1,"l")],125),
 ("Beverages","Juices & Nectars","Real","Litchi Juice",[(1,"l")],125),
 ("Beverages","Juices & Nectars","Tropicana","Orange Delight Juice",[(1,"l")],130),
 ("Beverages","Juices & Nectars","Tropicana","Mixed Fruit Delight",[(1,"l")],130),
 ("Beverages","Juices & Nectars","B Natural","Mixed Fruit Juice",[(1,"l")],118),
 ("Beverages","Mango Drinks","Maaza","Mango Drink",[(600,"ml"),(1.2,"l")],70),
 ("Beverages","Mango Drinks","Frooti","Mango Drink",[(600,"ml"),(1.2,"l")],68),
 ("Beverages","Mango Drinks","Slice","Mango Drink",[(600,"ml"),(1.2,"l")],70),
 ("Beverages","Energy & Sports","Sting","Energy Drink",[(250,"ml")],80),
 ("Beverages","Energy & Sports","Gatorade","Sports Drink Orange",[(500,"ml")],70),
 ("Beverages","Squash & Syrup","Rooh Afza","Sharbat",[(750,"ml")],240),
 ("Beverages","Squash & Syrup","Kissan","Mango Squash",[(750,"ml")],200),
 ("Beverages","Glucose & Powder","Glucon-D","Original Glucose Powder",[(450,"g"),(1,"kg")],250),
 ("Beverages","Glucose & Powder","Tang","Orange Drink Powder",[(500,"g")],420),

 # ---------------- 11. Personal Care ----------------
 ("Personal Care","Bathing Soap","Lux","Soft Glow Soap",[(100,"g"),(150,"g")],400),
 ("Personal Care","Bathing Soap","Lifebuoy","Total 10 Soap",[(100,"g"),(125,"g")],340),
 ("Personal Care","Bathing Soap","Dettol","Original Soap",[(100,"g"),(125,"g")],420),
 ("Personal Care","Bathing Soap","Pears","Pure & Gentle Soap",[(100,"g"),(125,"g")],620),
 ("Personal Care","Bathing Soap","Dove","Cream Beauty Bathing Bar",[(100,"g"),(125,"g")],640),
 ("Personal Care","Bathing Soap","Santoor","Sandal & Turmeric Soap",[(100,"g"),(125,"g")],380),
 ("Personal Care","Bathing Soap","Cinthol","Lime Soap",[(100,"g"),(125,"g")],390),
 ("Personal Care","Bathing Soap","Medimix","Ayurvedic Soap",[(125,"g")],400),
 ("Personal Care","Bathing Soap","Patanjali","Neem Kanti Body Cleanser",[(125,"g")],320),
 ("Personal Care","Shampoo","Head & Shoulders","Anti Dandruff Shampoo",[(180,"ml"),(340,"ml")],1000),
 ("Personal Care","Shampoo","Clinic Plus","Strong & Long Shampoo",[(175,"ml"),(340,"ml")],720),
 ("Personal Care","Shampoo","Dove","Intense Repair Shampoo",[(180,"ml"),(340,"ml")],1080),
 ("Personal Care","Shampoo","Sunsilk","Stunning Black Shine Shampoo",[(180,"ml"),(340,"ml")],780),
 ("Personal Care","Shampoo","Pantene","Hairfall Control Shampoo",[(180,"ml"),(340,"ml")],1020),
 ("Personal Care","Shampoo","Himalaya","Anti Hair Fall Shampoo",[(200,"ml"),(400,"ml")],900),
 ("Personal Care","Shampoo","Patanjali","Kesh Kanti Shampoo",[(200,"ml")],650),
 ("Personal Care","Hair Oil","Parachute","Advansed Jasmine Hair Oil",[(175,"ml"),(300,"ml")],620),
 ("Personal Care","Hair Oil","Dabur","Amla Hair Oil",[(180,"ml"),(275,"ml")],560),
 ("Personal Care","Hair Oil","Bajaj","Almond Drops Hair Oil",[(190,"ml"),(300,"ml")],700),
 ("Personal Care","Hair Oil","Patanjali","Kesh Kanti Hair Oil",[(100,"ml"),(200,"ml")],600),
 ("Personal Care","Hair Oil","Navratna","Cool Oil",[(200,"ml"),(300,"ml")],540),
 ("Personal Care","Oral Care","Colgate","Strong Teeth Toothpaste",[(100,"g"),(200,"g")],580),
 ("Personal Care","Oral Care","Colgate","MaxFresh Toothpaste",[(150,"g")],620),
 ("Personal Care","Oral Care","Close Up","Red Hot Toothpaste",[(150,"g")],600),
 ("Personal Care","Oral Care","Pepsodent","Germicheck Toothpaste",[(150,"g")],560),
 ("Personal Care","Oral Care","Dabur","Red Toothpaste",[(100,"g"),(200,"g")],590),
 ("Personal Care","Oral Care","Patanjali","Dant Kanti Toothpaste",[(100,"g"),(200,"g")],520),
 ("Personal Care","Oral Care","Colgate","ZigZag Toothbrush",[(2,"pcs")],35),
 ("Personal Care","Skin Care","Nivea","Soft Light Moisturiser",[(100,"ml")],1800),
 ("Personal Care","Skin Care","Ponds","Dreamflower Talc",[(100,"g"),(200,"g")],450),
 ("Personal Care","Skin Care","Vaseline","Intensive Care Body Lotion",[(200,"ml"),(400,"ml")],900),
 ("Personal Care","Skin Care","Himalaya","Purifying Neem Face Wash",[(100,"ml"),(150,"ml")],900),
 ("Personal Care","Skin Care","Boroline","Antiseptic Cream",[(20,"g")],2200),
 ("Personal Care","Shaving & Grooming","Gillette","Mach 3 Cartridge",[(2,"pcs")],200),
 ("Personal Care","Shaving & Grooming","Gillette","Shaving Foam",[(200,"g")],1500),
 ("Personal Care","Deodorant","Fogg","Scent Napoleon",[(100,"ml")],3000),
 ("Personal Care","Deodorant","Nivea","Deodorant Fresh Natural",[(150,"ml")],1300),
 ("Personal Care","Feminine Care","Whisper","Ultra Clean Sanitary Pads",[(15,"pcs")],13),
 ("Personal Care","Feminine Care","Stayfree","Secure Sanitary Pads",[(20,"pcs")],10),

 # ---------------- 12. Home Care & Cleaning ----------------
 ("Home Care & Cleaning","Detergent Powder","Surf Excel","Easy Wash Detergent Powder",[(500,"g"),(1,"kg"),(2,"kg")],130),
 ("Home Care & Cleaning","Detergent Powder","Ariel","Complete Detergent Powder",[(500,"g"),(1,"kg"),(2,"kg")],145),
 ("Home Care & Cleaning","Detergent Powder","Tide","Plus Detergent Powder",[(500,"g"),(1,"kg"),(2,"kg")],110),
 ("Home Care & Cleaning","Detergent Powder","Rin","Advanced Detergent Powder",[(500,"g"),(1,"kg")],95),
 ("Home Care & Cleaning","Detergent Powder","Nirma","Washing Powder",[(500,"g"),(1,"kg")],75),
 ("Home Care & Cleaning","Detergent Powder","Ghadi","Detergent Powder",[(1,"kg")],72),
 ("Home Care & Cleaning","Liquid Detergent","Surf Excel","Matic Front Load Liquid",[(1,"l"),(2,"l")],230),
 ("Home Care & Cleaning","Liquid Detergent","Ariel","Matic Liquid Detergent",[(1,"l")],245),
 ("Home Care & Cleaning","Detergent Bar","Rin","Detergent Bar",[(250,"g")],40),
 ("Home Care & Cleaning","Detergent Bar","Wheel","Detergent Bar",[(200,"g")],35),
 ("Home Care & Cleaning","Dishwash","Vim","Dishwash Bar",[(200,"g"),(300,"g")],55),
 ("Home Care & Cleaning","Dishwash","Vim","Dishwash Liquid Gel",[(250,"ml"),(500,"ml"),(750,"ml")],240),
 ("Home Care & Cleaning","Dishwash","Pril","Dishwash Liquid",[(425,"ml"),(750,"ml")],230),
 ("Home Care & Cleaning","Dishwash","Exo","Dishwash Bar",[(200,"g")],52),
 ("Home Care & Cleaning","Floor & Toilet","Lizol","Floor Cleaner Citrus",[(500,"ml"),(975,"ml")],200),
 ("Home Care & Cleaning","Floor & Toilet","Lizol","Floor Cleaner Lavender",[(975,"ml")],200),
 ("Home Care & Cleaning","Floor & Toilet","Harpic","Power Plus Toilet Cleaner",[(500,"ml"),(1,"l")],200),
 ("Home Care & Cleaning","Floor & Toilet","Domex","Toilet Cleaner",[(500,"ml"),(1,"l")],185),
 ("Home Care & Cleaning","Floor & Toilet","Colin","Glass Cleaner",[(500,"ml")],180),
 ("Home Care & Cleaning","Phenyl & Disinfectant","Dettol","Antiseptic Liquid",[(250,"ml"),(550,"ml")],440),
 ("Home Care & Cleaning","Phenyl & Disinfectant","Dettol","Disinfectant Surface Cleaner",[(500,"ml")],220),
 ("Home Care & Cleaning","Repellent","Good Knight","Activ+ Refill",[(45,"ml")],2000),
 ("Home Care & Cleaning","Repellent","All Out","Mosquito Repellent Refill",[(45,"ml")],1900),
 ("Home Care & Cleaning","Repellent","Hit","Cockroach Killer Spray",[(400,"ml")],600),
 ("Home Care & Cleaning","Freshener","Odonil","Room Freshener Block",[(50,"g")],1200),
 ("Home Care & Cleaning","Freshener","Ambi Pur","Air Freshener Refill",[(275,"ml")],1100),

 # ---------------- 13. Baby Care ----------------
 ("Baby Care","Diapers","Pampers","All Round Protection Pants Medium",[(9,"pcs"),(20,"pcs")],22),
 ("Baby Care","Diapers","Pampers","All Round Protection Pants Large",[(9,"pcs"),(20,"pcs")],24),
 ("Baby Care","Diapers","Huggies","Wonder Pants Medium",[(9,"pcs"),(20,"pcs")],21),
 ("Baby Care","Diapers","MamyPoko","Pants Extra Absorb Medium",[(10,"pcs"),(20,"pcs")],21),
 ("Baby Care","Baby Food","Cerelac","Wheat Apple Baby Cereal",[(300,"g")],1000),
 ("Baby Care","Baby Food","Cerelac","Rice Baby Cereal",[(300,"g")],1000),
 ("Baby Care","Baby Food","Nestlé","Nan Pro Infant Formula Stage 1",[(400,"g")],2100),
 ("Baby Care","Baby Bath & Skin","Johnson's","Baby Powder",[(100,"g"),(200,"g")],700),
 ("Baby Care","Baby Bath & Skin","Johnson's","Baby Soap",[(75,"g")],700),
 ("Baby Care","Baby Bath & Skin","Johnson's","Baby Shampoo",[(100,"ml"),(200,"ml")],900),
 ("Baby Care","Baby Bath & Skin","Himalaya","Baby Lotion",[(200,"ml")],750),
 ("Baby Care","Baby Wipes","Himalaya","Gentle Baby Wipes",[(72,"pcs")],3),
 ("Baby Care","Baby Wipes","Pampers","Baby Wipes Fresh Clean",[(64,"pcs")],4),

 # ---------------- 14. Dry Fruits & Cereals ----------------
 ("Dry Fruits & Cereals","Dry Fruits","Happilo","Premium Californian Almonds",[(200,"g"),(500,"g")],900),
 ("Dry Fruits & Cereals","Dry Fruits","Happilo","Premium Whole Cashews",[(200,"g"),(500,"g")],1000),
 ("Dry Fruits & Cereals","Dry Fruits","Nutraj","Californian Almonds",[(250,"g"),(500,"g")],880),
 ("Dry Fruits & Cereals","Dry Fruits","Nutraj","Walnut Kernels",[(200,"g")],1400),
 ("Dry Fruits & Cereals","Dry Fruits","Tata Sampann","Raisins Kishmish",[(200,"g"),(500,"g")],420),
 ("Dry Fruits & Cereals","Dry Fruits","Happilo","Dried Pistachios Salted",[(200,"g")],1500),
 ("Dry Fruits & Cereals","Dry Fruits","Vedaka","Whole Cashews",[(500,"g")],960),
 ("Dry Fruits & Cereals","Dry Fruits","Nutraj","Dates Seedless",[(500,"g")],300),
 ("Dry Fruits & Cereals","Breakfast Cereal","Kellogg's","Corn Flakes Original",[(250,"g"),(475,"g")],440),
 ("Dry Fruits & Cereals","Breakfast Cereal","Kellogg's","Chocos",[(250,"g"),(700,"g")],500),
 ("Dry Fruits & Cereals","Breakfast Cereal","Kellogg's","Muesli Fruit & Nut",[(500,"g")],600),
 ("Dry Fruits & Cereals","Breakfast Cereal","Bagrry's","Crunchy Muesli",[(500,"g"),(1,"kg")],560),
 ("Dry Fruits & Cereals","Breakfast Cereal","Saffola","Oats",[(500,"g"),(1,"kg")],200),
 ("Dry Fruits & Cereals","Breakfast Cereal","Quaker","Oats",[(400,"g"),(1,"kg")],220),
 ("Dry Fruits & Cereals","Breakfast Cereal","Bagrry's","White Oats",[(500,"g"),(1,"kg")],210),

 # ---------------- 15. Sauces, Pickles & Spreads ----------------
 ("Sauces, Pickles & Spreads","Ketchup & Sauces","Kissan","Fresh Tomato Ketchup",[(415,"g"),(850,"g")],200),
 ("Sauces, Pickles & Spreads","Ketchup & Sauces","Maggi","Rich Tomato Ketchup",[(500,"g"),(900,"g")],195),
 ("Sauces, Pickles & Spreads","Ketchup & Sauces","Maggi","Hot & Sweet Tomato Chilli Sauce",[(400,"g"),(1,"kg")],230),
 ("Sauces, Pickles & Spreads","Ketchup & Sauces","Ching's Secret","Schezwan Chutney",[(250,"g")],400),
 ("Sauces, Pickles & Spreads","Ketchup & Sauces","Ching's Secret","Red Chilli Sauce",[(200,"g")],320),
 ("Sauces, Pickles & Spreads","Ketchup & Sauces","Veeba","Tandoori Mayonnaise",[(250,"g")],440),
 ("Sauces, Pickles & Spreads","Ketchup & Sauces","Veeba","Eggless Mayonnaise",[(250,"g"),(650,"g")],400),
 ("Sauces, Pickles & Spreads","Pickles","Mother's Recipe","Mango Pickle",[(300,"g"),(500,"g")],320),
 ("Sauces, Pickles & Spreads","Pickles","Mother's Recipe","Mixed Pickle",[(300,"g")],320),
 ("Sauces, Pickles & Spreads","Pickles","Priya","Lime Pickle",[(300,"g")],300),
 ("Sauces, Pickles & Spreads","Pickles","Patanjali","Mixed Pickle",[(500,"g")],290),
 ("Sauces, Pickles & Spreads","Pickles","Nilon's","Mango Pickle",[(400,"g")],300),
 ("Sauces, Pickles & Spreads","Jam & Spreads","Kissan","Mixed Fruit Jam",[(200,"g"),(500,"g")],300),
 ("Sauces, Pickles & Spreads","Jam & Spreads","Kissan","Pineapple Jam",[(200,"g")],310),
 ("Sauces, Pickles & Spreads","Jam & Spreads","Nutella","Hazelnut Spread",[(180,"g"),(350,"g")],1700),
 ("Sauces, Pickles & Spreads","Jam & Spreads","Sundrop","Peanut Butter Creamy",[(200,"g"),(462,"g")],700),
 ("Sauces, Pickles & Spreads","Jam & Spreads","Pintola","All Natural Peanut Butter",[(350,"g")],750),
 ("Sauces, Pickles & Spreads","Chutney & Paste","Dabur","Hommade Ginger Garlic Paste",[(200,"g")],450),
 ("Sauces, Pickles & Spreads","Chutney & Paste","Dabur","Hommade Tomato Puree",[(200,"g")],300),

 # ---------------- 16. Breakfast & Ready-to-Eat ----------------
 ("Breakfast & Ready-to-Eat","Ready to Eat","MTR","Poha Ready to Eat",[(160,"g")],450),
 ("Breakfast & Ready-to-Eat","Ready to Eat","MTR","Upma Ready to Eat",[(160,"g")],450),
 ("Breakfast & Ready-to-Eat","Ready to Eat","MTR","Dal Makhani Ready to Eat",[(300,"g")],450),
 ("Breakfast & Ready-to-Eat","Ready to Eat","Haldiram's","Paneer Butter Masala Ready to Eat",[(300,"g")],470),
 ("Breakfast & Ready-to-Eat","Ready to Eat","Gits","Chole Ready to Eat",[(300,"g")],440),
 ("Breakfast & Ready-to-Eat","Batter & Frozen","iD Fresh","Idli Dosa Batter",[(1,"kg")],110),
 ("Breakfast & Ready-to-Eat","Batter & Frozen","iD Fresh","Malabar Parota",[(400,"g")],300),
 ("Breakfast & Ready-to-Eat","Batter & Frozen","McCain","French Fries",[(420,"g")],320),
 ("Breakfast & Ready-to-Eat","Batter & Frozen","McCain","Aloo Tikki",[(400,"g")],330),
 ("Breakfast & Ready-to-Eat","Papad & Fryums","Lijjat","Urad Papad",[(200,"g")],400),
 ("Breakfast & Ready-to-Eat","Papad & Fryums","Bikano","Masala Papad",[(200,"g")],380),

 # ---------------- 17. Pooja & Household Essentials ----------------
 ("Pooja & Household Essentials","Pooja Items","Cycle","Three in One Agarbatti",[(120,"pcs")],1),
 ("Pooja & Household Essentials","Pooja Items","Cycle","Rhythm Agarbatti",[(100,"pcs")],1.2),
 ("Pooja & Household Essentials","Pooja Items","Mangaldeep","Sandal Agarbatti",[(90,"pcs")],1.1),
 ("Pooja & Household Essentials","Pooja Items","Cycle","Camphor Tablets Kapur",[(50,"g")],1600),
 ("Pooja & Household Essentials","Pooja Items","Mangaldeep","Dhoop Sticks",[(15,"pcs")],4),
 ("Pooja & Household Essentials","Pooja Items","Cycle","Pooja Cotton Wicks Batti",[(100,"pcs")],0.4),
 ("Pooja & Household Essentials","Kitchen Essentials","Ezee","Garbage Bags Medium",[(30,"pcs")],4),
 ("Pooja & Household Essentials","Kitchen Essentials","Scotch-Brite","Scrub Pad",[(3,"pcs")],25),
 ("Pooja & Household Essentials","Kitchen Essentials","Vim","Steel Scrubber",[(2,"pcs")],20),
 ("Pooja & Household Essentials","Kitchen Essentials","Hindalco","Aluminium Foil",[(9,"pcs")],15),
 ("Pooja & Household Essentials","Kitchen Essentials","Origami","Kitchen Tissue Roll",[(2,"pcs")],60),
 ("Pooja & Household Essentials","Matches & Candles","Homelite","Safety Matches",[(10,"pcs")],2),

 # ---------------- 18. Chocolates & Confectionery ----------------
 ("Chocolates & Confectionery","Chocolate Bars","Cadbury","Dairy Milk Chocolate",[(50,"g"),(110,"g")],1000),
 ("Chocolates & Confectionery","Chocolate Bars","Cadbury","Dairy Milk Silk",[(60,"g"),(150,"g")],1300),
 ("Chocolates & Confectionery","Chocolate Bars","Cadbury","Fuse Chocolate",[(45,"g")],1100),
 ("Chocolates & Confectionery","Chocolate Bars","Nestlé","KitKat Chocolate",[(37,"g"),(75,"g")],1100),
 ("Chocolates & Confectionery","Chocolate Bars","Nestlé","Munch Chocolate",[(32,"g")],900),
 ("Chocolates & Confectionery","Chocolate Bars","Amul","Dark Chocolate 55%",[(150,"g")],900),
 ("Chocolates & Confectionery","Chocolate Bars","Cadbury","Perk Chocolate",[(30,"g")],900),
 ("Chocolates & Confectionery","Chocolate Bars","Cadbury","5 Star Chocolate",[(45,"g")],900),
 ("Chocolates & Confectionery","Candy & Toffee","Cadbury","Eclairs Toffee",[(100,"g"),(200,"g")],550),
 ("Chocolates & Confectionery","Candy & Toffee","Parle","Melody Toffee",[(100,"g")],500),
 ("Chocolates & Confectionery","Candy & Toffee","Nestlé","Polo Mint",[(50,"g")],600),
 ("Chocolates & Confectionery","Candy & Toffee","Perfetti","Alpenliebe Candy",[(100,"g")],520),
 ("Chocolates & Confectionery","Candy & Toffee","Perfetti","Center Fresh Chewing Gum",[(50,"g")],700),
 ("Chocolates & Confectionery","Candy & Toffee","Pulse","Kaccha Aam Candy",[(100,"g")],500),
 ("Chocolates & Confectionery","Gift Packs","Cadbury","Celebrations Assorted Chocolate",[(180,"g")],1600),

 # ---------------- 19. Water ----------------
 ("Water","Packaged Water","Bisleri","Packaged Drinking Water",[(500,"ml"),(1,"l"),(2,"l")],10),
 ("Water","Packaged Water","Kinley","Packaged Drinking Water",[(500,"ml"),(1,"l"),(2,"l")],10),
 ("Water","Packaged Water","Aquafina","Packaged Drinking Water",[(500,"ml"),(1,"l")],10),
 ("Water","Packaged Water","Bailley","Packaged Drinking Water",[(1,"l"),(2,"l")],9),
 ("Water","Mineral & Soda","Bisleri","Soda Water",[(750,"ml")],25),
 ("Water","Mineral & Soda","Kinley","Club Soda",[(750,"ml")],25),

 # ---------------- 20. Other Kirana Essentials ----------------
 ("Other Kirana Essentials","Dry Snacks & Sattu","Patanjali","Sattu",[(500,"g")],110),
 ("Other Kirana Essentials","Dry Snacks & Sattu","Tata Sampann","Roasted Chana",[(200,"g")],250),
 ("Other Kirana Essentials","Baking","Weikfield","Baking Powder",[(100,"g")],450),
 ("Other Kirana Essentials","Baking","Weikfield","Corn Flour",[(100,"g")],400),
 ("Other Kirana Essentials","Baking","Blue Bird","Custard Powder Vanilla",[(100,"g")],420),
 ("Other Kirana Essentials","Baking","Dr. Oetker","Cocoa Powder",[(50,"g")],2000),
 ("Other Kirana Essentials","Dry Coconut & Seeds","Tata Sampann","Poppy Seeds Khus Khus",[(100,"g")],1600),
 ("Other Kirana Essentials","Dry Coconut & Seeds","Patanjali","Flax Seeds",[(200,"g")],300),
 ("Other Kirana Essentials","Vinegar & Essence","Weikfield","Vinegar",[(200,"ml")],250),
 ("Other Kirana Essentials","Vinegar & Essence","Blue Bird","Vanilla Essence",[(20,"ml")],3500),
 ("Other Kirana Essentials","Health Supplements","Dabur","Chyawanprash",[(500,"g"),(1,"kg")],440),
 ("Other Kirana Essentials","Health Supplements","Patanjali","Chyawanprash",[(500,"g"),(1,"kg")],400),
 ("Other Kirana Essentials","Health Supplements","Himalaya","Septilin Tablets",[(60,"pcs")],3),
 ("Other Kirana Essentials","Stationery & Misc","Camlin","Pen Blue",[(5,"pcs")],10),
 ("Other Kirana Essentials","Stationery & Misc","Classmate","Notebook Ruled",[(1,"pcs")],45),

 # ---------------- flavour and pack-size depth ----------------
 # Real kirana shelves carry several flavours of the same line. These are
 # additional REAL products from brands already above, not padding.
 ("Snacks & Namkeen","Chips & Crisps","Lay's","Spanish Tomato Tango Chips",[(52,"g"),(90,"g")],440),
 ("Snacks & Namkeen","Chips & Crisps","Lay's","Sizzling Hot Chips",[(52,"g")],440),
 ("Snacks & Namkeen","Chips & Crisps","Lay's","Chile Limon Chips",[(52,"g")],440),
 ("Snacks & Namkeen","Chips & Crisps","Lay's","Wafer Style Simply Salted",[(52,"g")],440),
 ("Snacks & Namkeen","Chips & Crisps","Bingo","Mad Angles Tomato Mischief",[(66,"g")],420),
 ("Snacks & Namkeen","Chips & Crisps","Bingo","Original Style Salted Chips",[(52,"g")],420),
 ("Snacks & Namkeen","Chips & Crisps","Kurkure","Chilli Chatka",[(70,"g")],400),
 ("Snacks & Namkeen","Chips & Crisps","Kurkure","Solid Masti Puffcorn",[(52,"g")],460),
 ("Snacks & Namkeen","Chips & Crisps","Too Yumm","Veggie Stix Tomato",[(45,"g")],600),
 ("Snacks & Namkeen","Namkeen","Haldiram's","Nut Cracker",[(200,"g")],290),
 ("Snacks & Namkeen","Namkeen","Haldiram's","Punjabi Tadka",[(200,"g")],255),
 ("Snacks & Namkeen","Namkeen","Haldiram's","Falahari Mixture",[(200,"g")],300),
 ("Snacks & Namkeen","Namkeen","Bikano","Aloo Bhujia",[(200,"g"),(400,"g")],235),
 ("Snacks & Namkeen","Namkeen","Bikano","Peanuts Masala",[(200,"g")],240),
 ("Snacks & Namkeen","Namkeen","Balaji","Chana Jor Garam",[(200,"g")],225),
 ("Snacks & Namkeen","Namkeen","Haldiram's","Sev Murmura",[(200,"g")],230),

 ("Instant Food & Noodles","Noodles","Maggi","Chicken Noodles",[(70,"g")],215),
 ("Instant Food & Noodles","Noodles","Maggi","Masala Cuppa Noodles",[(70,"g")],290),
 ("Instant Food & Noodles","Noodles","Yippee","Saucy Masala Noodles",[(70,"g")],195),
 ("Instant Food & Noodles","Noodles","Top Ramen","Masala Noodles",[(70,"g"),(280,"g")],190),
 ("Instant Food & Noodles","Noodles","Ching's Secret","Schezwan Instant Noodles",[(60,"g"),(240,"g")],230),
 ("Instant Food & Noodles","Noodles","Ching's Secret","Hakka Instant Noodles",[(60,"g")],230),
 ("Instant Food & Noodles","Soups","Knorr","Mixed Vegetable Soup",[(43,"g")],1150),
 ("Instant Food & Noodles","Soups","Knorr","Tomato Chatpata Soup",[(53,"g")],1050),
 ("Instant Food & Noodles","Ready Mixes","MTR","Dosa Mix",[(500,"g")],175),
 ("Instant Food & Noodles","Ready Mixes","MTR","Vada Mix",[(500,"g")],180),
 ("Instant Food & Noodles","Ready Mixes","Gits","Rava Idli Mix",[(200,"g")],380),
 ("Instant Food & Noodles","Ready Mixes","Gits","Jalebi Mix",[(200,"g")],400),

 ("Beverages","Juices & Nectars","Real","Guava Juice",[(1,"l")],125),
 ("Beverages","Juices & Nectars","Real","Pomegranate Juice",[(1,"l")],180),
 ("Beverages","Juices & Nectars","Real","Apple Juice",[(1,"l")],125),
 ("Beverages","Juices & Nectars","Real","Cranberry Juice",[(1,"l")],150),
 ("Beverages","Juices & Nectars","Tropicana","Apple Delight",[(1,"l")],130),
 ("Beverages","Juices & Nectars","Tropicana","Guava Delight",[(1,"l")],130),
 ("Beverages","Juices & Nectars","B Natural","Guava Juice",[(1,"l")],118),
 ("Beverages","Squash & Syrup","Kissan","Orange Squash",[(750,"ml")],200),
 ("Beverages","Squash & Syrup","Rasna","Instant Drink Mix Orange",[(500,"g")],380),
 ("Beverages","Squash & Syrup","Rasna","Instant Drink Mix Mango",[(500,"g")],380),
 ("Beverages","Glucose & Powder","Glucon-D","Nimbu Pani Glucose Powder",[(450,"g")],260),
 ("Beverages","Glucose & Powder","Tang","Mango Drink Powder",[(500,"g")],420),

 ("Chocolates & Confectionery","Chocolate Bars","Cadbury","Dairy Milk Roast Almond",[(36,"g")],1200),
 ("Chocolates & Confectionery","Chocolate Bars","Cadbury","Dairy Milk Crackle",[(36,"g")],1200),
 ("Chocolates & Confectionery","Chocolate Bars","Nestlé","Milkybar",[(25,"g")],1200),
 ("Chocolates & Confectionery","Chocolate Bars","Amul","Milk Chocolate",[(150,"g")],800),
 ("Chocolates & Confectionery","Chocolate Bars","Amul","Fruit & Nut Chocolate",[(150,"g")],900),
 ("Chocolates & Confectionery","Candy & Toffee","Perfetti","Mentos Mint",[(50,"g")],700),
 ("Chocolates & Confectionery","Candy & Toffee","Perfetti","Chatar Patar Candy",[(100,"g")],500),
 ("Chocolates & Confectionery","Candy & Toffee","Cadbury","Gems",[(35,"g")],1100),

 ("Biscuits & Bakery","Cream Biscuits","Britannia","Treat Jim Jam Orange",[(150,"g")],105),
 ("Biscuits & Bakery","Cream Biscuits","Sunfeast","Bounce Orange Cream",[(100,"g")],95),
 ("Biscuits & Bakery","Cream Biscuits","Parle","20-20 Cashew Cookies",[(100,"g"),(200,"g")],90),
 ("Biscuits & Bakery","Cream Biscuits","Parle","Happy Happy Choco Chip",[(100,"g")],110),
 ("Biscuits & Bakery","Cookies","Britannia","Good Day Chocochip Cookies",[(100,"g"),(250,"g")],105),
 ("Biscuits & Bakery","Cookies","Britannia","Little Hearts",[(75,"g")],150),
 ("Biscuits & Bakery","Digestive & Health","Britannia","NutriChoice Oats Cookies",[(150,"g")],140),
 ("Biscuits & Bakery","Rusk & Bread","Britannia","Whole Wheat Bread",[(400,"g")],120),
 ("Biscuits & Bakery","Rusk & Bread","Harvest Gold","White Bread",[(400,"g")],110),

 ("Personal Care","Bathing Soap","Lux","Rose Glow Soap",[(100,"g"),(125,"g")],400),
 ("Personal Care","Bathing Soap","Lux","Velvet Glow Soap",[(100,"g")],400),
 ("Personal Care","Bathing Soap","Lifebuoy","Lemon Fresh Soap",[(100,"g")],340),
 ("Personal Care","Bathing Soap","Cinthol","Original Soap",[(100,"g")],390),
 ("Personal Care","Bathing Soap","Godrej","No 1 Sandal Soap",[(100,"g"),(150,"g")],300),
 ("Personal Care","Bathing Soap","Dove","Sensitive Skin Bathing Bar",[(100,"g")],660),
 ("Personal Care","Shampoo","Clinic Plus","Anti Dandruff Shampoo",[(175,"ml")],740),
 ("Personal Care","Shampoo","Sunsilk","Perfect Straight Shampoo",[(180,"ml")],780),
 ("Personal Care","Shampoo","Head & Shoulders","Cool Menthol Shampoo",[(180,"ml")],1000),
 ("Personal Care","Hair Oil","Parachute","Pure Coconut Hair Oil",[(250,"ml")],600),
 ("Personal Care","Hair Oil","Dabur","Almond Hair Oil",[(200,"ml")],640),
 ("Personal Care","Oral Care","Colgate","Vedshakti Toothpaste",[(100,"g"),(200,"g")],620),
 ("Personal Care","Oral Care","Colgate","Active Salt Toothpaste",[(100,"g"),(200,"g")],560),
 ("Personal Care","Oral Care","Sensodyne","Fresh Mint Toothpaste",[(70,"g"),(150,"g")],1400),
 ("Personal Care","Skin Care","Nivea","Body Milk Nourishing Lotion",[(200,"ml"),(400,"ml")],1100),
 ("Personal Care","Skin Care","Ponds","White Beauty Face Wash",[(100,"g")],1100),
 ("Personal Care","Skin Care","Himalaya","Moisturizing Aloe Vera Face Wash",[(100,"ml")],900),
 ("Personal Care","Skin Care","Vaseline","Petroleum Jelly Original",[(85,"ml")],1400),
 ("Personal Care","Deodorant","Fogg","Scent Xpressio",[(100,"ml")],3000),
 ("Personal Care","Deodorant","Park Avenue","Deodorant Good Morning",[(150,"ml")],1200),
 ("Personal Care","Feminine Care","Whisper","Choice Ultra Sanitary Pads",[(15,"pcs")],11),
 ("Personal Care","Feminine Care","Sofy","Bodyfit Sanitary Pads",[(15,"pcs")],11),

 ("Home Care & Cleaning","Detergent Powder","Surf Excel","Quick Wash Detergent Powder",[(500,"g"),(1,"kg")],150),
 ("Home Care & Cleaning","Detergent Powder","Nirma","Advance Detergent Powder",[(1,"kg")],85),
 ("Home Care & Cleaning","Liquid Detergent","Surf Excel","Matic Top Load Liquid",[(1,"l"),(2,"l")],220),
 ("Home Care & Cleaning","Liquid Detergent","Genteel","Liquid Detergent",[(1,"l")],215),
 ("Home Care & Cleaning","Dishwash","Vim","Dishwash Liquid Lemon",[(500,"ml")],240),
 ("Home Care & Cleaning","Floor & Toilet","Lizol","Floor Cleaner Pine",[(975,"ml")],200),
 ("Home Care & Cleaning","Floor & Toilet","Harpic","Toilet Cleaner Lemon",[(1,"l")],195),
 ("Home Care & Cleaning","Fabric Care","Comfort","After Wash Fabric Conditioner",[(400,"ml"),(860,"ml")],220),
 ("Home Care & Cleaning","Fabric Care","Ujala","Supreme Liquid Whitener",[(75,"ml")],1300),
 ("Home Care & Cleaning","Fabric Care","Robin","Blue Powder",[(100,"g")],400),
 ("Home Care & Cleaning","Repellent","Good Knight","Gold Flash Refill",[(45,"ml")],2100),
 ("Home Care & Cleaning","Freshener","Odonil","Zipper Air Freshener",[(10,"g")],5000),

 ("Dairy & Eggs","Milk","Amul","Buffalo A2 Milk",[(500,"ml")],72),
 ("Dairy & Eggs","Curd & Paneer","Amul","Greek Yogurt Plain",[(200,"g")],300),
 ("Dairy & Eggs","Butter & Cheese","Amul","Cheese Spread Pepper",[(200,"g")],620),
 ("Dairy & Eggs","Ice Cream","Amul","Vanilla Ice Cream",[(700,"ml")],220),
 ("Dairy & Eggs","Ice Cream","Amul","Butterscotch Ice Cream",[(700,"ml")],230),
 ("Dairy & Eggs","Ice Cream","Mother Dairy","Chocolate Ice Cream",[(700,"ml")],230),
 ("Dairy & Eggs","Ice Cream","Vadilal","Kesar Pista Ice Cream",[(500,"ml")],260),

 ("Tea, Coffee & Milk Drinks","Tea","Tata","Tea Elaichi Chai",[(250,"g")],620),
 ("Tea, Coffee & Milk Drinks","Tea","Red Label","Natural Care Tea",[(250,"g"),(500,"g")],560),
 ("Tea, Coffee & Milk Drinks","Tea","Wagh Bakri","Masala Tea",[(250,"g")],560),
 ("Tea, Coffee & Milk Drinks","Coffee","Nescafé","Gold Blend Coffee",[(50,"g")],5000),
 ("Tea, Coffee & Milk Drinks","Milk Drinks","Bournvita","Little Champs",[(500,"g")],500),

 ("Atta, Rice & Dal","Atta","Aashirvaad","Atta with Multigrains Ragi",[(5,"kg")],88),
 ("Atta, Rice & Dal","Rice","India Gate","Basmati Rice Super",[(1,"kg"),(5,"kg")],185),
 ("Atta, Rice & Dal","Rice","Daawat","Biryani Basmati Rice",[(1,"kg")],150),
 ("Atta, Rice & Dal","Pulses","Tata Sampann","Kabuli Chana",[(500,"g"),(1,"kg")],135),
 ("Atta, Rice & Dal","Pulses","Tata Sampann","Rajma",[(500,"g"),(1,"kg")],170),
 ("Atta, Rice & Dal","Poha & Sabudana","Patanjali","Sabudana",[(500,"g")],92),

 ("Masala & Spices","Blended Masala","MDH","Meat Masala",[(100,"g")],900),
 ("Masala & Spices","Blended Masala","MDH","Rajmah Masala",[(100,"g")],880),
 ("Masala & Spices","Blended Masala","Everest","Tikka Masala",[(100,"g")],920),
 ("Masala & Spices","Blended Masala","Aachi","Garam Masala",[(100,"g")],780),
 ("Masala & Spices","Ground Spices","Aachi","Chilli Powder",[(100,"g"),(500,"g")],600),
 ("Masala & Spices","Whole Spices","Tata Sampann","Ajwain",[(100,"g")],420),

 ("Oils & Ghee","Cooking Oil","Fortune","Groundnut Oil",[(1,"l")],220),
 ("Oils & Ghee","Cooking Oil","Saffola","Total Refined Oil",[(1,"l")],210),
 ("Oils & Ghee","Ghee","Amul","Cow Ghee",[(500,"ml"),(1,"l")],660),
 ("Oils & Ghee","Cooking Oil","Patanjali","Refined Sunflower Oil",[(1,"l")],155),

 ("Dry Fruits & Cereals","Breakfast Cereal","Kellogg's","Special K Original",[(285,"g")],620),
 ("Dry Fruits & Cereals","Dry Fruits","Happilo","Dried Black Raisins",[(250,"g")],440),
 ("Dry Fruits & Cereals","Dry Fruits","Nutraj","Apricot Dried",[(250,"g")],700),

 ("Sauces, Pickles & Spreads","Ketchup & Sauces","Veeba","Sandwich Spread",[(300,"g")],420),
 ("Sauces, Pickles & Spreads","Pickles","Mother's Recipe","Lemon Pickle",[(300,"g")],310),
 ("Sauces, Pickles & Spreads","Jam & Spreads","Kissan","Strawberry Jam",[(200,"g")],320),

 ("Baby Care","Diapers","Pampers","Premium Care Pants Small",[(20,"pcs")],23),
 ("Baby Care","Baby Food","Cerelac","Mixed Fruit Baby Cereal",[(300,"g")],1000),

 ("Water","Packaged Water","Bisleri","Packaged Drinking Water Jar",[(20,"l")],4),
]
